%%%%%%%%%%%%%%%%%%%%   path: classes/+utils/@plottools   %%%%%%%%%%%%%%%%%%%%
%
%   <a href="matlab:help classes/+utils/@plottools/addPlotProvenance">classes/+utils/@plottools/addPlotProvenance</a>          -  adds a discrete text label to a figure with details of
%   <a href="matlab:help classes/+utils/@plottools/addRepositoryPatch">classes/+utils/@plottools/addRepositoryPatch</a>         - ADDPLOTPROVENANCE adds a discrete text label to a figure with details of
%   <a href="matlab:help classes/+utils/@plottools/adjustErrorbarTick">classes/+utils/@plottools/adjustErrorbarTick</a>         -  Adjust the width of y-errorbars.
%   <a href="matlab:help classes/+utils/@plottools/allLines">classes/+utils/@plottools/allLines</a>                   -  Set all the line styles and widths on the current axes
%   <a href="matlab:help classes/+utils/@plottools/allMarkers">classes/+utils/@plottools/allMarkers</a>                 -  Set all the markers on the current axes
%   <a href="matlab:help classes/+utils/@plottools/allgrid">classes/+utils/@plottools/allgrid</a>                    -  Set all the grids to 'state'
%   <a href="matlab:help classes/+utils/@plottools/allowedLinestyles">classes/+utils/@plottools/allowedLinestyles</a>          -  returns a cell-array of valid MATLAB line styles.
%   <a href="matlab:help classes/+utils/@plottools/allowedMarkers">classes/+utils/@plottools/allowedMarkers</a>             -  returns a cell-array of valid MATLAB markers.
%   <a href="matlab:help classes/+utils/@plottools/allxaxis">classes/+utils/@plottools/allxaxis</a>                   - ALLXSCALE Set all the x scales on the current figure.
%   <a href="matlab:help classes/+utils/@plottools/allxlabel">classes/+utils/@plottools/allxlabel</a>                  -  Set all the x-axis labels on the current figure.
%   <a href="matlab:help classes/+utils/@plottools/allxscale">classes/+utils/@plottools/allxscale</a>                  -  Set all the x scales on the current figure.
%   <a href="matlab:help classes/+utils/@plottools/allyaxis">classes/+utils/@plottools/allyaxis</a>                   -  Set all the yaxis ranges on the current figure.
%   <a href="matlab:help classes/+utils/@plottools/allylabel">classes/+utils/@plottools/allylabel</a>                  -  Set all the y-axis labels on the current figure.
%   <a href="matlab:help classes/+utils/@plottools/allyscale">classes/+utils/@plottools/allyscale</a>                  -  Set all the Y scales on the current figure.
%   <a href="matlab:help classes/+utils/@plottools/backupDefaultPlotSettings">classes/+utils/@plottools/backupDefaultPlotSettings</a>  -  Backup the current default plot settings.
%   <a href="matlab:help classes/+utils/@plottools/box">classes/+utils/@plottools/box</a>                        -  applies box to all the given axes handles.
%   <a href="matlab:help classes/+utils/@plottools/cacheObjectInUserData">classes/+utils/@plottools/cacheObjectInUserData</a>      -  cache a copy of the object in the figure handle's
%   <a href="matlab:help classes/+utils/@plottools/consolidatePlot">classes/+utils/@plottools/consolidatePlot</a>            -  creates a collection object from the objects contained
%   <a href="matlab:help classes/+utils/@plottools/convertXunits">classes/+utils/@plottools/convertXunits</a>              - -----------------------------------------------
%   <a href="matlab:help classes/+utils/@plottools/cscale">classes/+utils/@plottools/cscale</a>                     -  Set the color range of the current figure
%   <a href="matlab:help classes/+utils/@plottools/datacursormode">classes/+utils/@plottools/datacursormode</a>             - Display the position of the data cursor
%   <a href="matlab:help classes/+utils/@plottools/errorbarxy">classes/+utils/@plottools/errorbarxy</a>                 -  Customizable error bar plot in X and Y direction
%   <a href="matlab:help classes/+utils/@plottools/fixAxisLabel">classes/+utils/@plottools/fixAxisLabel</a>               -  performs some substitutions on the axis label string.
%   <a href="matlab:help classes/+utils/@plottools/getAxes">classes/+utils/@plottools/getAxes</a>                    -  gets an array of axes from the given figure handle.
%   <a href="matlab:help classes/+utils/@plottools/getLegends">classes/+utils/@plottools/getLegends</a>                 -  gets an array of legends from the given figure handle.
%   <a href="matlab:help classes/+utils/@plottools/hold">classes/+utils/@plottools/hold</a>                       -  applies hold to all the given axes handles.
%   <a href="matlab:help classes/+utils/@plottools/horizontalLine">classes/+utils/@plottools/horizontalLine</a>             -  plots a horizontal line(s) to an axes handle.
%   <a href="matlab:help classes/+utils/@plottools/islinespec">classes/+utils/@plottools/islinespec</a>                 -  checks a string to the line spec syntax.
%   <a href="matlab:help classes/+utils/@plottools/label">classes/+utils/@plottools/label</a>                      -  makes the input string into a suitable string for using on plots.
%   <a href="matlab:help classes/+utils/@plottools/legendAdd">classes/+utils/@plottools/legendAdd</a>                  -  Add a string to the current legend.
%   <a href="matlab:help classes/+utils/@plottools/makeDraft">classes/+utils/@plottools/makeDraft</a>                  -  labels a figure as draft, or not.
%   <a href="matlab:help classes/+utils/@plottools/msuptitle">classes/+utils/@plottools/msuptitle</a>                  -  Puts a title above all subplots.
%   <a href="matlab:help classes/+utils/@plottools/plottools">classes/+utils/@plottools/plottools</a>                  -  class for tools to manipulate the current object/figure/axis.
%   <a href="matlab:help classes/+utils/@plottools/restoreDefaultPlotSettings">classes/+utils/@plottools/restoreDefaultPlotSettings</a> -  Restore the saved plot settings.
%   <a href="matlab:help classes/+utils/@plottools/retrieveFigure">classes/+utils/@plottools/retrieveFigure</a>             -  retreives a figure plist from an LTPDA repository.
%   <a href="matlab:help classes/+utils/@plottools/setLegendLocation">classes/+utils/@plottools/setLegendLocation</a>          -  gets an array of legends from the given figure handle
%   <a href="matlab:help classes/+utils/@plottools/submitFigure">classes/+utils/@plottools/submitFigure</a>               -  submits the given figure to an LTPDA repository.
%   <a href="matlab:help classes/+utils/@plottools/verticalLine">classes/+utils/@plottools/verticalLine</a>               -  plots a vertical line(s) to an axes handle.
%   <a href="matlab:help classes/+utils/@plottools/xaxis">classes/+utils/@plottools/xaxis</a>                      -  Set the X axis range of the current figure
%   <a href="matlab:help classes/+utils/@plottools/xlim">classes/+utils/@plottools/xlim</a>                       -  applies xlim to all the given axes handles.
%   <a href="matlab:help classes/+utils/@plottools/xscale">classes/+utils/@plottools/xscale</a>                     -  Set the X scale of the current axis
%   <a href="matlab:help classes/+utils/@plottools/xticks">classes/+utils/@plottools/xticks</a>                     -  set the input vector as the x-ticks of the current axis.
%   <a href="matlab:help classes/+utils/@plottools/yaxis">classes/+utils/@plottools/yaxis</a>                      -  Set the Y axis range of the current figure
%   <a href="matlab:help classes/+utils/@plottools/ylim">classes/+utils/@plottools/ylim</a>                       -  applies ylim to all the given axes handles.
%   <a href="matlab:help classes/+utils/@plottools/yscale">classes/+utils/@plottools/yscale</a>                     -  Set the Y scale of the current axis
%   <a href="matlab:help classes/+utils/@plottools/yticks">classes/+utils/@plottools/yticks</a>                     -  set the input vector as the y-ticks of the current axis.
%   <a href="matlab:help classes/+utils/@plottools/zaxis">classes/+utils/@plottools/zaxis</a>                      -  Set the Z axis range of the current figure
%   <a href="matlab:help classes/+utils/@plottools/zscale">classes/+utils/@plottools/zscale</a>                     -  Set the Z scale of the current axis
