%%%%%%%%%%%%%%%%%%%%   class: collection   %%%%%%%%%%%%%%%%%%%%
%
%   <a href="matlab:help collection/addObjects">collection/addObjects</a>               -  adds the given objects to the collection.
%   <a href="matlab:help collection/attachToDom">collection/attachToDom</a>              - % Create empty collection node with the attribute 'shape'
%   <a href="matlab:help collection/char">collection/char</a>                     -  convert a collection object into a string.
%   <a href="matlab:help collection/cohere">collection/cohere</a>                   -  estimates the coherence between time-series objects in a collection object.
%   <a href="matlab:help collection/collection">collection/collection</a>               -  constructor for collection class.
%   <a href="matlab:help collection/copy">collection/copy</a>                     -  makes a (deep) copy of the input collection objects.
%   <a href="matlab:help collection/cpsd">collection/cpsd</a>                     -  estimates the cross-spectral density between time-series objects in a collection object.
%   <a href="matlab:help collection/disp">collection/disp</a>                     -  overloads display functionality for collection objects.
%   <a href="matlab:help collection/filter">collection/filter</a>                   -  overrides the filter function for analysis objects in a collection object.
%   <a href="matlab:help collection/filtfilt">collection/filtfilt</a>                 -  overrides the filtfilt function for analysis objects in a collection object.
%   <a href="matlab:help collection/fromDom">collection/fromDom</a>                  - % Get shape
%   <a href="matlab:help collection/fromInput">collection/fromInput</a>                - Construct a collection object from ltpda_uoh objects.
%   <a href="matlab:help collection/fromRepository">collection/fromRepository</a>           - Retrieve a ltpda_uo from a repository
%   <a href="matlab:help collection/fromStruct">collection/fromStruct</a>               -  creates from a structure a COLLECTION object.
%   <a href="matlab:help collection/generateConstructorPlist">collection/generateConstructorPlist</a> -  generates a PLIST from the properties which can rebuild the object.
%   <a href="matlab:help collection/getObjectAtIndex">collection/getObjectAtIndex</a>         -  index into the inner objects of one collection object.
%   <a href="matlab:help collection/getObjectByName">collection/getObjectByName</a>          -  returns an inside object selected by the name.
%   <a href="matlab:help collection/getObjectsOfClass">collection/getObjectsOfClass</a>        -  returns all objects of the specified class in a collection-object.
%   <a href="matlab:help collection/identifyInsideObjs">collection/identifyInsideObjs</a>       -  Static method which identify the inside objects and configuration PLISTs.
%   <a href="matlab:help collection/iplot">collection/iplot</a>                    -  calls ao/iplot on all inner ao objects.
%   <a href="matlab:help collection/lincom">collection/lincom</a>                   -  make a linear combination of objects within the collection
%   <a href="matlab:help collection/loadobj">collection/loadobj</a>                  -  is called by the load function for user objects.
%   <a href="matlab:help collection/nobjs">collection/nobjs</a>                    -  Returns the number of objects in the inner object array.
%   <a href="matlab:help collection/objTypes">collection/objTypes</a>                 -  returns a cell array of the class types for each object in the
%   <a href="matlab:help collection/plot">collection/plot</a>                     -  the collection objects.
%   <a href="matlab:help collection/plotTrends">collection/plotTrends</a>               -  plots the trend collections produced by ao/trends.
%   <a href="matlab:help collection/removeObjectAtIndex">collection/removeObjectAtIndex</a>      -  removes the object at the specified position from the collection.
%   <a href="matlab:help collection/saveAllObjects">collection/saveAllObjects</a>           -  index into the inner objects of one collection object.
%   <a href="matlab:help collection/setNames">collection/setNames</a>                 -  Sets the property 'names' of a collection object.
%   <a href="matlab:help collection/setObjectAtIndex">collection/setObjectAtIndex</a>         -  sets an input object to the collection.
%   <a href="matlab:help collection/setObjs">collection/setObjs</a>                  -  sets the 'objs' property of a collection object.
%   <a href="matlab:help collection/subsasgn">collection/subsasgn</a>                 -  overloads the setting behaviour for collection objects.
%   <a href="matlab:help collection/subsref">collection/subsref</a>                  -  overloads the referencing behaviour for collection objects.
%   <a href="matlab:help collection/summaryReport">collection/summaryReport</a>            -  generates an HTML report about the inner objects.
%   <a href="matlab:help collection/tfe">collection/tfe</a>                      -  estimates the transfer function between time-series objects in a collection object.
%   <a href="matlab:help collection/toCell">collection/toCell</a>                   -  toCells the objects in a collection and sets them to the given output
%   <a href="matlab:help collection/unpack">collection/unpack</a>                   -  unpacks the objects in a collection and sets them to the given output
%   <a href="matlab:help collection/update_struct">collection/update_struct</a>            -  update the input structure to the current ltpda version
%   <a href="matlab:help collection/wrapperEval">collection/wrapperEval</a>              - % loop over inner objects
