% GETIMEZONE Get the list of supported time zones.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% DESCRIPTION: GETIMEZONE Get the cell array containing the list of
%                         supported time zones.
%
% CALL:        timezones = getTimezone()
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function timezones = getTimezone(varargin)

  if nargin>0, utils.helper.msg(0, 'warning: the function getTimezone accepts no input, but some were passed.'); 
  end
  
  timezones = {'UTC'    ; ...
               'CET'    ; ...
               'PST'    ; ...
               'CST'    ; ...
               'EST'    ; ...
               'JST'    ; ...
               'GMT-12' ; ...
               'GMT-11' ; ...
               'GMT-10' ; ...
               'GMT-09' ; ...
               'GMT-08' ; ...
               'GMT-07' ; ...
               'GMT-06' ; ...
               'GMT-05' ; ...
               'GMT-04' ; ...
               'GMT-03' ; ...
               'GMT-02' ; ...
               'GMT-01' ; ...
               'GMT'    ; ...
               'GMT+01' ; ...
               'GMT+02' ; ...
               'GMT+03' ; ...
               'GMT+04' ; ...
               'GMT+05' ; ...
               'GMT+06' ; ...
               'GMT+07' ; ...
               'GMT+08' ; ...
               'GMT+09' ; ...
               'GMT+10' ; ...
               'GMT+11' ; ...
               'GMT+12' };

end

