%%%%%%%%%%%%%%%%%%%%   class: ltpda_uoh   %%%%%%%%%%%%%%%%%%%%
%
%   <a href="matlab:help ltpda_uoh/addHistory">ltpda_uoh/addHistory</a>               -  Add a history-object to the ltpda_uo object.
%   <a href="matlab:help ltpda_uoh/addHistoryWoChangingUUID">ltpda_uoh/addHistoryWoChangingUUID</a> -  Add a history-object to the ltpda_uo object.
%   <a href="matlab:help ltpda_uoh/attachToDom">ltpda_uoh/attachToDom</a>              - % Add hist
%   <a href="matlab:help ltpda_uoh/clearHistory">ltpda_uoh/clearHistory</a>             -  Clears the history of an object with history.
%   <a href="matlab:help ltpda_uoh/copy">ltpda_uoh/copy</a>                     -  copies all fields of the ltpda_uoh class to the new object.
%   <a href="matlab:help ltpda_uoh/created">ltpda_uoh/created</a>                  -  Returns a time object of the last modification.
%   <a href="matlab:help ltpda_uoh/creator">ltpda_uoh/creator</a>                  -  Extract the creator(s) from the history.
%   <a href="matlab:help ltpda_uoh/csvGenerateData">ltpda_uoh/csvGenerateData</a>          -  Default method to convert a ltpda_uoh-object into csv data.
%   <a href="matlab:help ltpda_uoh/csvexport">ltpda_uoh/csvexport</a>                -  Exports the data of an object to a csv file.
%   <a href="matlab:help ltpda_uoh/fromDom">ltpda_uoh/fromDom</a>                  - %%%%%%%%%% Call super-class
%   <a href="matlab:help ltpda_uoh/fromModel">ltpda_uoh/fromModel</a>                -  Construct an a built in model
%   <a href="matlab:help ltpda_uoh/fromRepository">ltpda_uoh/fromRepository</a>           - Retrieve a ltpda_uo from a repository
%   <a href="matlab:help ltpda_uoh/fromStruct">ltpda_uoh/fromStruct</a>               -  sets all properties which are defined in the ltpda_uoh class from the structure to the input object.
%   <a href="matlab:help ltpda_uoh/index">ltpda_uoh/index</a>                    -  index into a 'ltpda_uoh' object array or matrix. This properly captures the history.
%   <a href="matlab:help ltpda_uoh/loadobj">ltpda_uoh/loadobj</a>                  - % This is an old-type ltpda object from disk, so we don't need to
%   <a href="matlab:help ltpda_uoh/ltpda_uoh">ltpda_uoh/ltpda_uoh</a>                -  is the abstract ltpda base class for ltpda user object classes with history
%   <a href="matlab:help ltpda_uoh/plot">ltpda_uoh/plot</a>                     -  plots the user object on a figure.
%   <a href="matlab:help ltpda_uoh/prepareSinfoForSubmit">ltpda_uoh/prepareSinfoForSubmit</a>    -  This method prepend the timespan as a XML-String to the submission structure.
%   <a href="matlab:help ltpda_uoh/rebuild">ltpda_uoh/rebuild</a>                  -  rebuilds the input objects using the history.
%   <a href="matlab:help ltpda_uoh/report">ltpda_uoh/report</a>                   -  generates an HTML report about the input objects.
%   <a href="matlab:help ltpda_uoh/requirements">ltpda_uoh/requirements</a>             -  Returns a list of LTPDA extension requirements for a given object.
%   <a href="matlab:help ltpda_uoh/saveobj">ltpda_uoh/saveobj</a>                  - % MATLAB does a double pass save, firs calculating the size, then doing
%   <a href="matlab:help ltpda_uoh/setHist">ltpda_uoh/setHist</a>                  -  Set the property 'hist'
%   <a href="matlab:help ltpda_uoh/setObjectProperties">ltpda_uoh/setObjectProperties</a>      -  sets the object properties of an ltpda_uoh object.
%   <a href="matlab:help ltpda_uoh/setPlotAxes">ltpda_uoh/setPlotAxes</a>              -  sets the 'axes' property of a the object's plotinfo.
%   <a href="matlab:help ltpda_uoh/setPlotColor">ltpda_uoh/setPlotColor</a>             -  sets the color of a the object's plotinfo.
%   <a href="matlab:help ltpda_uoh/setPlotFigure">ltpda_uoh/setPlotFigure</a>            -  sets the 'figure' property of a the object's plotinfo.
%   <a href="matlab:help ltpda_uoh/setPlotFillmarker">ltpda_uoh/setPlotFillmarker</a>        -  defines if the plot function fill the marker or not.
%   <a href="matlab:help ltpda_uoh/setPlotLineStyle">ltpda_uoh/setPlotLineStyle</a>         -  sets the linestyle of a the object's plotinfo.
%   <a href="matlab:help ltpda_uoh/setPlotLinewidth">ltpda_uoh/setPlotLinewidth</a>         -  sets the linewidth of a the object's plotinfo.
%   <a href="matlab:help ltpda_uoh/setPlotMarker">ltpda_uoh/setPlotMarker</a>            -  sets the marker of a the object's plotinfo.
%   <a href="matlab:help ltpda_uoh/setPlotMarkerEdgeColor">ltpda_uoh/setPlotMarkerEdgeColor</a>   -  sets the color of a the object's marker edge.
%   <a href="matlab:help ltpda_uoh/setPlotMarkerFaceColor">ltpda_uoh/setPlotMarkerFaceColor</a>   -  sets the color of a the object's marker face.
%   <a href="matlab:help ltpda_uoh/setPlotMarkersize">ltpda_uoh/setPlotMarkersize</a>        -  sets the markersize of a the object's plotinfo.
%   <a href="matlab:help ltpda_uoh/setPlotinfo">ltpda_uoh/setPlotinfo</a>              -  sets the 'plotinfo' property of a ltpda_uoh object.
%   <a href="matlab:help ltpda_uoh/setPlottingStyle">ltpda_uoh/setPlottingStyle</a>         -  sets the style property of a the object's plotinfo.
%   <a href="matlab:help ltpda_uoh/setProcinfo">ltpda_uoh/setProcinfo</a>              -  sets the 'procinfo' property of a ltpda_uoh object.
%   <a href="matlab:help ltpda_uoh/setProperties">ltpda_uoh/setProperties</a>            -  set different properties of an object.
%   <a href="matlab:help ltpda_uoh/setPropertyValue">ltpda_uoh/setPropertyValue</a>         - (No help available)
%   <a href="matlab:help ltpda_uoh/setShowsErrors">ltpda_uoh/setShowsErrors</a>           -  sets the 'showErrors' property of a the object's plotinfo.
%   <a href="matlab:help ltpda_uoh/setTimespan">ltpda_uoh/setTimespan</a>              -  sets the 'timespan' property of a ltpda_uoh object.
%   <a href="matlab:help ltpda_uoh/string">ltpda_uoh/string</a>                   -  writes a command string that can be used to recreate the input object(s).
%   <a href="matlab:help ltpda_uoh/testCallerIsMethod">ltpda_uoh/testCallerIsMethod</a>       -  hidden static method which tests the 'internal' command of a LTPDA-function.
%   <a href="matlab:help ltpda_uoh/type">ltpda_uoh/type</a>                     -  converts the input objects to MATLAB functions.
%   <a href="matlab:help ltpda_uoh/viewHistory">ltpda_uoh/viewHistory</a>              -  Displays the history of an object as a dot-view or a MATLAB figure.
