%%%%%%%%%%%%%%%%%%%%   class: specwin   %%%%%%%%%%%%%%%%%%%%
%
%   <a href="matlab:help specwin/attachToDom">specwin/attachToDom</a>         - % Create empty specwin node with the attribute 'shape'
%   <a href="matlab:help specwin/char">specwin/char</a>                -  convert a specwin object into a string.
%   <a href="matlab:help specwin/copy">specwin/copy</a>                -  makes a (deep) copy of the input specwin objects.
%   <a href="matlab:help specwin/disp">specwin/disp</a>                -  overloads display functionality for specwin objects.
%   <a href="matlab:help specwin/fromDom">specwin/fromDom</a>             - % Get shape
%   <a href="matlab:help specwin/fromStruct">specwin/fromStruct</a>          -  creates from a structure a SPECWIN object.
%   <a href="matlab:help specwin/get_window">specwin/get_window</a>          -  returns the required window function as a structure.
%   <a href="matlab:help specwin/kaiser_alpha">specwin/kaiser_alpha</a>        -  returns the alpha parameter that gives the required input
%   <a href="matlab:help specwin/kaiser_flatness">specwin/kaiser_flatness</a>     -  returns the flatness in dB of the central bin of a kaiser 
%   <a href="matlab:help specwin/kaiser_nenbw">specwin/kaiser_nenbw</a>        -  returns the normalized noise-equivalent bandwidth for a
%   <a href="matlab:help specwin/kaiser_rov">specwin/kaiser_rov</a>          -  returns the recommended overlap for a Kaiser window with
%   <a href="matlab:help specwin/kaiser_w3db">specwin/kaiser_w3db</a>         -  returns the 3dB bandwidth in bins of a kaiser window with
%   <a href="matlab:help specwin/loadobj">specwin/loadobj</a>             -  is called by the load function for user objects.
%   <a href="matlab:help specwin/plot">specwin/plot</a>                -  plots a specwin object.
%   <a href="matlab:help specwin/specwin">specwin/specwin</a>             -  spectral window object class constructor.
%   <a href="matlab:help specwin/string">specwin/string</a>              -  writes a command string that can be used to recreate the input window object.
%   <a href="matlab:help specwin/toPlist">specwin/toPlist</a>             -  creates a plist representing the specwin object.
%   <a href="matlab:help specwin/update_struct">specwin/update_struct</a>       -  update the input structure to the current ltpda version
%   <a href="matlab:help specwin/win_bartlett">specwin/win_bartlett</a>        -  returns Bartlett window, with N points.
%   <a href="matlab:help specwin/win_bh92">specwin/win_bh92</a>            -  returns BH92 window, with N points.
%   <a href="matlab:help specwin/win_fthp">specwin/win_fthp</a>            -  returns FTHP window, with N points.
%   <a href="matlab:help specwin/win_ftni">specwin/win_ftni</a>            -  returns FTNI window, with N points.
%   <a href="matlab:help specwin/win_ftsrs">specwin/win_ftsrs</a>           -  returns FTSRS window, with N points.
%   <a href="matlab:help specwin/win_hamming">specwin/win_hamming</a>         -  returns Hamming window, with N points.
%   <a href="matlab:help specwin/win_hanning">specwin/win_hanning</a>         -  returns Hanning window, with N points.
%   <a href="matlab:help specwin/win_hft116d">specwin/win_hft116d</a>         -  returns HFT116D window, with N points.
%   <a href="matlab:help specwin/win_hft144d">specwin/win_hft144d</a>         -  returns HFT144D window, with N points.
%   <a href="matlab:help specwin/win_hft169d">specwin/win_hft169d</a>         -  returns HFT169D window, with N points.
%   <a href="matlab:help specwin/win_hft196d">specwin/win_hft196d</a>         -  returns HFT196D window, with N points.
%   <a href="matlab:help specwin/win_hft223d">specwin/win_hft223d</a>         -  returns HFT223D window, with N points.
%   <a href="matlab:help specwin/win_hft248d">specwin/win_hft248d</a>         -  returns HFT248D window, with N points.
%   <a href="matlab:help specwin/win_hft70">specwin/win_hft70</a>           -  returns HFT70 window, with N points.
%   <a href="matlab:help specwin/win_hft90d">specwin/win_hft90d</a>          -  returns HFT90D window, with N points.
%   <a href="matlab:help specwin/win_hft95">specwin/win_hft95</a>           -  returns HFT95 window, with N points.
%   <a href="matlab:help specwin/win_kaiser">specwin/win_kaiser</a>          -  returns Kaiser window, with N points and psll peak sidelobe level.
%   <a href="matlab:help specwin/win_levelledhanning">specwin/win_levelledhanning</a> -  returns Hanning window, with N points and levelCoef levelling order
%   <a href="matlab:help specwin/win_nuttall3">specwin/win_nuttall3</a>        -  returns Nuttall3 window, with N points.
%   <a href="matlab:help specwin/win_nuttall3a">specwin/win_nuttall3a</a>       -  returns Nuttall3a window, with N points.
%   <a href="matlab:help specwin/win_nuttall3b">specwin/win_nuttall3b</a>       -  returns Nuttall3b window, with N points.
%   <a href="matlab:help specwin/win_nuttall4">specwin/win_nuttall4</a>        -  returns Nuttall4 window, with N points.
%   <a href="matlab:help specwin/win_nuttall4a">specwin/win_nuttall4a</a>       -  returns Nuttall4a window, with N points.
%   <a href="matlab:help specwin/win_nuttall4b">specwin/win_nuttall4b</a>       -  returns Nuttall4b window, with N points.
%   <a href="matlab:help specwin/win_nuttall4c">specwin/win_nuttall4c</a>       -  returns Nuttall4c window, with N points.
%   <a href="matlab:help specwin/win_rectangular">specwin/win_rectangular</a>     -  returns rectangular window, with N points.
%   <a href="matlab:help specwin/win_sft3f">specwin/win_sft3f</a>           -  returns SFT3F window, with N points.
%   <a href="matlab:help specwin/win_sft3m">specwin/win_sft3m</a>           -  returns SFT3M window, with N points.
%   <a href="matlab:help specwin/win_sft4f">specwin/win_sft4f</a>           -  returns SFT4F window, with N points.
%   <a href="matlab:help specwin/win_sft4m">specwin/win_sft4m</a>           -  returns SFT4M window, with N points.
%   <a href="matlab:help specwin/win_sft5f">specwin/win_sft5f</a>           -  returns SFT5F window, with N points.
%   <a href="matlab:help specwin/win_sft5m">specwin/win_sft5m</a>           -  returns SFT5M window, with N points.
%   <a href="matlab:help specwin/win_welch">specwin/win_welch</a>           -  returns Welch window, with N points.
