%%%%%%%%%%%%%%%%%%%%   path: classes/+utils/@math   %%%%%%%%%%%%%%%%%%%%
%
%   <a href="matlab:help classes/+utils/@math/Chi2cdf">classes/+utils/@math/Chi2cdf</a>                      - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes/+utils/@math/Chi2inv">classes/+utils/@math/Chi2inv</a>                      - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes/+utils/@math/Fcdf">classes/+utils/@math/Fcdf</a>                         - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes/+utils/@math/Finv">classes/+utils/@math/Finv</a>                         - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes/+utils/@math/Fpdf">classes/+utils/@math/Fpdf</a>                         - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes/+utils/@math/Ftest">classes/+utils/@math/Ftest</a>                        -  perfomes an F-Test.
%   <a href="matlab:help classes/+utils/@math/Kurt">classes/+utils/@math/Kurt</a>                         - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes/+utils/@math/Normcdf">classes/+utils/@math/Normcdf</a>                      - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes/+utils/@math/Norminv">classes/+utils/@math/Norminv</a>                      - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes/+utils/@math/Rcovmat">classes/+utils/@math/Rcovmat</a>                      - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes/+utils/@math/SFtest">classes/+utils/@math/SFtest</a>                       -  perfomes a Spectral F-Test on PSDs.
%   <a href="matlab:help classes/+utils/@math/SKcriticalvalues">classes/+utils/@math/SKcriticalvalues</a>             - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes/+utils/@math/Skew">classes/+utils/@math/Skew</a>                         - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes/+utils/@math/autocfit">classes/+utils/@math/autocfit</a>                     -  performs a fitting loop to identify model order and parameters.
%   <a href="matlab:help classes/+utils/@math/autodfit">classes/+utils/@math/autodfit</a>                     -  perform a fitting loop to identify model order and parameters.
%   <a href="matlab:help classes/+utils/@math/blwhitenoise">classes/+utils/@math/blwhitenoise</a>                 -  return a band limited gaussian distributed white noise
%   <a href="matlab:help classes/+utils/@math/boxplot">classes/+utils/@math/boxplot</a>                      -  draw box plot on data
%   <a href="matlab:help classes/+utils/@math/cauchy">classes/+utils/@math/cauchy</a>                       - (No help available)
%   <a href="matlab:help classes/+utils/@math/cdfplot">classes/+utils/@math/cdfplot</a>                      -  makes cumulative distribution plot
%   <a href="matlab:help classes/+utils/@math/chi2">classes/+utils/@math/chi2</a>                         - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes/+utils/@math/chisquare_ssm_td">classes/+utils/@math/chisquare_ssm_td</a>             - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes/+utils/@math/chop">classes/+utils/@math/chop</a>                         - (No help available)
%   <a href="matlab:help classes/+utils/@math/computeDftPeriodogram">classes/+utils/@math/computeDftPeriodogram</a>        -  compute periodogram with dft
%   <a href="matlab:help classes/+utils/@math/computepsd">classes/+utils/@math/computepsd</a>                   - Slight modification of original MATLAB's computepsd to include correct scaling for the variance, i.e var(a*x) = a^2*var(x)
%   <a href="matlab:help classes/+utils/@math/corr2cov">classes/+utils/@math/corr2cov</a>                     - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes/+utils/@math/cov2corr">classes/+utils/@math/cov2corr</a>                     - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes/+utils/@math/cpf">classes/+utils/@math/cpf</a>                          -  finds the partial fraction expansion of the ratio of two polynomials A(s)/B(s).
%   <a href="matlab:help classes/+utils/@math/cpsd">classes/+utils/@math/cpsd</a>                         - UTILS.MATH.CPSD: Pure Matlab function that performs the CPSD using LTPDA machinery
%   <a href="matlab:help classes/+utils/@math/crank">classes/+utils/@math/crank</a>                        -  calculate ranks for Spearman correlation
%   <a href="matlab:help classes/+utils/@math/csd2tf">classes/+utils/@math/csd2tf</a>                       -  Input cross spectral density matrix and output stable transfer function 
%   <a href="matlab:help classes/+utils/@math/csd2tf2">classes/+utils/@math/csd2tf2</a>                      -  Input cross spectral density matrix and output stable transfer function 
%   <a href="matlab:help classes/+utils/@math/ctfit">classes/+utils/@math/ctfit</a>                        -  fits a continuous model to a frequency response.
%   <a href="matlab:help classes/+utils/@math/ctmult">classes/+utils/@math/ctmult</a>                       - % Multiplication function designed for the
%   <a href="matlab:help classes/+utils/@math/deg2rad">classes/+utils/@math/deg2rad</a>                      -  Convert degrees to radians
%   <a href="matlab:help classes/+utils/@math/dft">classes/+utils/@math/dft</a>                          -  Compute discrete fourier transform at a given frequency
%   <a href="matlab:help classes/+utils/@math/diffStepFish">classes/+utils/@math/diffStepFish</a>                 - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes/+utils/@math/diffStepFish_1x1">classes/+utils/@math/diffStepFish_1x1</a>             - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes/+utils/@math/dispersion_1x1">classes/+utils/@math/dispersion_1x1</a>               - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes/+utils/@math/dispersion_2x2">classes/+utils/@math/dispersion_2x2</a>               - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes/+utils/@math/downsampleSpectrum">classes/+utils/@math/downsampleSpectrum</a>           -  spectrum in order to ensure independence between frequency
%   <a href="matlab:help classes/+utils/@math/drawSampleM">classes/+utils/@math/drawSampleM</a>                  - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes/+utils/@math/drawSampleT">classes/+utils/@math/drawSampleT</a>                  -   Draw a sample from the Student's t distribution
%   <a href="matlab:help classes/+utils/@math/dtfit">classes/+utils/@math/dtfit</a>                        -  fits a discrete model to a frequency response.
%   <a href="matlab:help classes/+utils/@math/ecdf">classes/+utils/@math/ecdf</a>                         -  Compute empirical cumulative distribution function
%   <a href="matlab:help classes/+utils/@math/eigcsd">classes/+utils/@math/eigcsd</a>                       -  calculates TFs from 2D cross-correlated spectra.
%   <a href="matlab:help classes/+utils/@math/eigpsd">classes/+utils/@math/eigpsd</a>                       -  calculates TFs from 2D cross-correlated spectra.
%   <a href="matlab:help classes/+utils/@math/fdfilt_delay_core">classes/+utils/@math/fdfilt_delay_core</a>            -  core method to implement fractional delay filtering
%   <a href="matlab:help classes/+utils/@math/fftdelay_core">classes/+utils/@math/fftdelay_core</a>                -  applies a delay to a timeseries using the FFT/IFFT method
%   <a href="matlab:help classes/+utils/@math/filtfilt_filterbank">classes/+utils/@math/filtfilt_filterbank</a>          -  computes filtfilt for filterbank objects
%   <a href="matlab:help classes/+utils/@math/filtpz">classes/+utils/@math/filtpz</a>                       - (No help available)
%   <a href="matlab:help classes/+utils/@math/findShapeParamKStestSpectrum">classes/+utils/@math/findShapeParamKStestSpectrum</a> -  find shape parameter for kstest on the
%   <a href="matlab:help classes/+utils/@math/fisher">classes/+utils/@math/fisher</a>                       - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes/+utils/@math/fisher_1x1">classes/+utils/@math/fisher_1x1</a>                   - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes/+utils/@math/fisher_2x2">classes/+utils/@math/fisher_2x2</a>                   - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes/+utils/@math/fitPrior">classes/+utils/@math/fitPrior</a>                     - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes/+utils/@math/fminsearchbnd_core">classes/+utils/@math/fminsearchbnd_core</a>           - --------------------------------------------------------------------------
%   <a href="matlab:help classes/+utils/@math/fpsder">classes/+utils/@math/fpsder</a>                       -  performs the numeric time derivative
%   <a href="matlab:help classes/+utils/@math/fq2ri">classes/+utils/@math/fq2ri</a>                        -  Convert frequency/Q pole/zero representation into real
%   <a href="matlab:help classes/+utils/@math/fq2ri2">classes/+utils/@math/fq2ri2</a>                       -  Convert frequency/Q pole/zero representation into real
%   <a href="matlab:help classes/+utils/@math/free_flight_ode">classes/+utils/@math/free_flight_ode</a>              - % we cannot look up the parameter each time because it takes too long
%   <a href="matlab:help classes/+utils/@math/freqCorr">classes/+utils/@math/freqCorr</a>                     -  Compute correlation between frequency bins
%   <a href="matlab:help classes/+utils/@math/gammacdf">classes/+utils/@math/gammacdf</a>                     - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes/+utils/@math/gammapdf">classes/+utils/@math/gammapdf</a>                     - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes/+utils/@math/getCorr">classes/+utils/@math/getCorr</a>                      - (No help available)
%   <a href="matlab:help classes/+utils/@math/getdc">classes/+utils/@math/getdc</a>                        -  get the DC gain factor for a pole-zero model
%   <a href="matlab:help classes/+utils/@math/getfftfreq">classes/+utils/@math/getfftfreq</a>                   - GETFFTFREQ: get frequencies for fft
%   <a href="matlab:help classes/+utils/@math/getinitstate">classes/+utils/@math/getinitstate</a>                 - (No help available)
%   <a href="matlab:help classes/+utils/@math/getjacobian">classes/+utils/@math/getjacobian</a>                  -  Calculate Jacobian of a given model function.
%   <a href="matlab:help classes/+utils/@math/getk">classes/+utils/@math/getk</a>                         -  get the mathematical gain factor for a pole-zero model
%   <a href="matlab:help classes/+utils/@math/heaviside">classes/+utils/@math/heaviside</a>                    - (No help available)
%   <a href="matlab:help classes/+utils/@math/iirinit">classes/+utils/@math/iirinit</a>                      -  defines the initial state of an IIR filter.
%   <a href="matlab:help classes/+utils/@math/intfact">classes/+utils/@math/intfact</a>                      -  computes integer factorisation
%   <a href="matlab:help classes/+utils/@math/isequal">classes/+utils/@math/isequal</a>                      -  test if two matrices are equal to within the given tolerance.
%   <a href="matlab:help classes/+utils/@math/jr2cov">classes/+utils/@math/jr2cov</a>                       -  Calculates coefficients covariance matrix from Jacobian and Residuals.
%   <a href="matlab:help classes/+utils/@math/kstest">classes/+utils/@math/kstest</a>                       -  perform the Kolmogorov - Smirnov statistical hypothesis test
%   <a href="matlab:help classes/+utils/@math/linfit">classes/+utils/@math/linfit</a>                       -  returns the fit parameters for a linear fit of the form  y = m*x + b.
%   <a href="matlab:help classes/+utils/@math/linfitsvd">classes/+utils/@math/linfitsvd</a>                    - Linear fit with singular value decomposition
%   <a href="matlab:help classes/+utils/@math/linlsqsvd">classes/+utils/@math/linlsqsvd</a>                    -  Linear least squares with singular value decomposition
%   <a href="matlab:help classes/+utils/@math/logLmath">classes/+utils/@math/logLmath</a>                     - (No help available)
%   <a href="matlab:help classes/+utils/@math/loglikelihood">classes/+utils/@math/loglikelihood</a>                - (No help available)
%   <a href="matlab:help classes/+utils/@math/loglikelihood_matrix">classes/+utils/@math/loglikelihood_matrix</a>         - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes/+utils/@math/loglikelihood_ssm">classes/+utils/@math/loglikelihood_ssm</a>            - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes/+utils/@math/loglikelihood_ssm_td">classes/+utils/@math/loglikelihood_ssm_td</a>         - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes/+utils/@math/loglikelihood_td">classes/+utils/@math/loglikelihood_td</a>             - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes/+utils/@math/lp2z">classes/+utils/@math/lp2z</a>                         -  converts a continous TF in to a discrete TF.
%   <a href="matlab:help classes/+utils/@math/math">classes/+utils/@math/math</a>                         -  helper class for math utility functions.
%   <a href="matlab:help classes/+utils/@math/mhsample">classes/+utils/@math/mhsample</a>                     - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes/+utils/@math/mhsample_td">classes/+utils/@math/mhsample_td</a>                  - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes/+utils/@math/mtxiirresp">classes/+utils/@math/mtxiirresp</a>                   -  calculate iir resp by matrix product
%   <a href="matlab:help classes/+utils/@math/mtxiirresp2">classes/+utils/@math/mtxiirresp2</a>                  -  calculate iir resp by matrix product
%   <a href="matlab:help classes/+utils/@math/mtxratresp2">classes/+utils/@math/mtxratresp2</a>                  - MTXIIRRESP calculate rational resp by matrix product
%   <a href="matlab:help classes/+utils/@math/mult">classes/+utils/@math/mult</a>                         - % Multiplication function designed specially for the
%   <a href="matlab:help classes/+utils/@math/music">classes/+utils/@math/music</a>                        -   Implements the heart of the MUSIC algorithm of line spectra estimation.
%   <a href="matlab:help classes/+utils/@math/ndeigcsd">classes/+utils/@math/ndeigcsd</a>                     -  calculates TFs from ND cross-correlated spectra.
%   <a href="matlab:help classes/+utils/@math/normalPDF">classes/+utils/@math/normalPDF</a>                    - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes/+utils/@math/overlapCorr">classes/+utils/@math/overlapCorr</a>                  -  Compute correlation introduced by segment overlapping
%   <a href="matlab:help classes/+utils/@math/pf2ss">classes/+utils/@math/pf2ss</a>                        -  Convert partial fraction models to state space matrices
%   <a href="matlab:help classes/+utils/@math/pfallps">classes/+utils/@math/pfallps</a>                      -  all pass filtering in order to stabilize TF poles and zeros.
%   <a href="matlab:help classes/+utils/@math/pfallps2">classes/+utils/@math/pfallps2</a>                     -  all pass filtering to stabilize TF poles and zeros.
%   <a href="matlab:help classes/+utils/@math/pfallpsyms">classes/+utils/@math/pfallpsyms</a>                   - (No help available)
%   <a href="matlab:help classes/+utils/@math/pfallpsyms2">classes/+utils/@math/pfallpsyms2</a>                  -  all pass filtering to stabilize TF poles and zeros.
%   <a href="matlab:help classes/+utils/@math/pfallpsymz">classes/+utils/@math/pfallpsymz</a>                   -  all pass filtering in order to stabilize TF poles and zeros.
%   <a href="matlab:help classes/+utils/@math/pfallpsymz2">classes/+utils/@math/pfallpsymz2</a>                  -  all pass filtering to stabilize TF poles and zeros.
%   <a href="matlab:help classes/+utils/@math/pfallpz">classes/+utils/@math/pfallpz</a>                      -  all pass filtering to stabilize TF poles and zeros.
%   <a href="matlab:help classes/+utils/@math/pfallpz2">classes/+utils/@math/pfallpz2</a>                     -  all pass filtering to stabilize TF poles and zeros.
%   <a href="matlab:help classes/+utils/@math/pfresp">classes/+utils/@math/pfresp</a>                       -  returns frequency response of a partial fraction TF.
%   <a href="matlab:help classes/+utils/@math/phase">classes/+utils/@math/phase</a>                        -  return the phase in degrees for a given complex input.
%   <a href="matlab:help classes/+utils/@math/ppplot">classes/+utils/@math/ppplot</a>                       -  makes probability-probability plot
%   <a href="matlab:help classes/+utils/@math/psd">classes/+utils/@math/psd</a>                          - UTILS.MATH.PSD: Pure Matlab function that performs the PSD using LTPDA machinery
%   <a href="matlab:help classes/+utils/@math/psd2tf">classes/+utils/@math/psd2tf</a>                       -  Input power spectral density (psd) and output a stable and minimum
%   <a href="matlab:help classes/+utils/@math/psd2wf">classes/+utils/@math/psd2wf</a>                       - PSD2WF: Input power spectral density (psd) and output a corresponding
%   <a href="matlab:help classes/+utils/@math/psdvectorfit">classes/+utils/@math/psdvectorfit</a>                 - AUTOCFIT performs a fitting loop to identify model order and parameters.
%   <a href="matlab:help classes/+utils/@math/psdzfit">classes/+utils/@math/psdzfit</a>                      - PSDZFIT: Fit discrete partial fraction model to PSD
%   <a href="matlab:help classes/+utils/@math/psre">classes/+utils/@math/psre</a>                         - (No help available)
%   <a href="matlab:help classes/+utils/@math/pzmodel2SSMats">classes/+utils/@math/pzmodel2SSMats</a>               - % computing the A matrix
%   <a href="matlab:help classes/+utils/@math/qqplot">classes/+utils/@math/qqplot</a>                       -  makes quantile-quantile plot
%   <a href="matlab:help classes/+utils/@math/rand">classes/+utils/@math/rand</a>                         -  return a random number between r1 and r2
%   <a href="matlab:help classes/+utils/@math/randelement">classes/+utils/@math/randelement</a>                  - RANDELEMENT(VECTOR,J) returns J random samples chosen in the VECTOR array.
%   <a href="matlab:help classes/+utils/@math/randomWalkGen">classes/+utils/@math/randomWalkGen</a>                - Generate a random walk
%   <a href="matlab:help classes/+utils/@math/regularizePSDForFit">classes/+utils/@math/regularizePSDForFit</a>          - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes/+utils/@math/ri2fq">classes/+utils/@math/ri2fq</a>                        -  Convert complex pole/zero into frequency/Q pole/zero representation.
%   <a href="matlab:help classes/+utils/@math/rjsample">classes/+utils/@math/rjsample</a>                     - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes/+utils/@math/rootmusic">classes/+utils/@math/rootmusic</a>                    -    Computes the frequencies and powers of sinusoids via the
%   <a href="matlab:help classes/+utils/@math/roundn">classes/+utils/@math/roundn</a>                       -   Round to multiple of 10^n
%   <a href="matlab:help classes/+utils/@math/slopefit">classes/+utils/@math/slopefit</a>                     -  returns the fit parameters for a linear fit of the form  y = m*x.
%   <a href="matlab:help classes/+utils/@math/spcorr">classes/+utils/@math/spcorr</a>                       -  calculate Spearman Rank-Order Correlation Coefficient
%   <a href="matlab:help classes/+utils/@math/spflat">classes/+utils/@math/spflat</a>                       -  measures the flatness of a given spectrum
%   <a href="matlab:help classes/+utils/@math/startpoles">classes/+utils/@math/startpoles</a>                   -  defines starting poles for fitting procedures ctfit, dtfit.
%   <a href="matlab:help classes/+utils/@math/stnr">classes/+utils/@math/stnr</a>                         - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes/+utils/@math/stopfit">classes/+utils/@math/stopfit</a>                      -  verify fit accuracy checking for specified condition.
%   <a href="matlab:help classes/+utils/@math/stpdf">classes/+utils/@math/stpdf</a>                        -   Probability density function for Student's T distribution
%   <a href="matlab:help classes/+utils/@math/unitStep">classes/+utils/@math/unitStep</a>                     - (No help available)
%   <a href="matlab:help classes/+utils/@math/unwrapdeg">classes/+utils/@math/unwrapdeg</a>                    -  Unwrap a phase vector given in degrees.
%   <a href="matlab:help classes/+utils/@math/vcfit">classes/+utils/@math/vcfit</a>                        -  Fits continuous models to frequency responses
%   <a href="matlab:help classes/+utils/@math/vdfit">classes/+utils/@math/vdfit</a>                        - VDFIT: Fit discrete models to frequency responses
%   <a href="matlab:help classes/+utils/@math/welchdft">classes/+utils/@math/welchdft</a>                     -  welch method with dft
%   <a href="matlab:help classes/+utils/@math/welchscale">classes/+utils/@math/welchscale</a>                   -  scales the output of welch to be in the required units
%   <a href="matlab:help classes/+utils/@math/wfun">classes/+utils/@math/wfun</a>                         -  defines weighting factor for fitting procedures ctfit, dtfit.
%   <a href="matlab:help classes/+utils/@math/xCovmat">classes/+utils/@math/xCovmat</a>                      - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help classes/+utils/@math/ymcd">classes/+utils/@math/ymcd</a>                         - (No help available)
