%%%%%%%%%%%%%%%%%%%%   class: ao   %%%%%%%%%%%%%%%%%%%%
%
%   <a href="matlab:help ao/abs">ao/abs</a>                      -  overloads the Absolute value method for analysis objects.
%   <a href="matlab:help ao/acos">ao/acos</a>                     -  overloads the acos method for analysis objects.
%   <a href="matlab:help ao/all">ao/all</a>                      -  overloads the all operator for analysis objects. True if all elements 
%   <a href="matlab:help ao/and">ao/and</a>                      -  (&) overloads the and (&) method for analysis objects.
%   <a href="matlab:help ao/angle">ao/angle</a>                    -  overloads the angle operator for analysis objects.
%   <a href="matlab:help ao/any">ao/any</a>                      -  overloads the any operator for analysis objects. True if any element 
%   <a href="matlab:help ao/ao">ao/ao</a>                       -  analysis object class constructor.
%   <a href="matlab:help ao/ao2numMatrices">ao/ao2numMatrices</a>           -  transforms AO objects to numerical matrices.
%   <a href="matlab:help ao/applymethod">ao/applymethod</a>              -  to the analysis object
%   <a href="matlab:help ao/applyoperator">ao/applyoperator</a>            -  to the analysis object
%   <a href="matlab:help ao/asin">ao/asin</a>                     -  overloads the asin method for analysis objects.
%   <a href="matlab:help ao/atan">ao/atan</a>                     -  overloads the atan method for analysis objects.
%   <a href="matlab:help ao/atan2">ao/atan2</a>                    -  overloads the atan2 operator for analysis objects. Four quadrant inverse tangent.
%   <a href="matlab:help ao/attachToDom">ao/attachToDom</a>              - % Create empty ao node with the attribute 'shape'
%   <a href="matlab:help ao/average">ao/average</a>                  -  averages aos point-by-point
%   <a href="matlab:help ao/bandpass">ao/bandpass</a>                 -  AOs containing time-series data.
%   <a href="matlab:help ao/bandreject">ao/bandreject</a>               -  AOs containing time-series data.
%   <a href="matlab:help ao/bicohere">ao/bicohere</a>                 -  computes the bicoherence of two input time-series
%   <a href="matlab:help ao/bilinfit">ao/bilinfit</a>                 -  is a linear fitting tool
%   <a href="matlab:help ao/bin_data">ao/bin_data</a>                 -  rebins aos data, on logarithmic scale, linear scale, or arbitrarly chosen.
%   <a href="matlab:help ao/blrms">ao/blrms</a>                    -  computes band-limited RMS trends of the input time-series.
%   <a href="matlab:help ao/buildWhitener1D">ao/buildWhitener1D</a>          -  builds a whitening filter based on the input frequency-series.
%   <a href="matlab:help ao/cast">ao/cast</a>                     -  - converts the numeric values in an AO to the data type specified by type.
%   <a href="matlab:help ao/cat">ao/cat</a>                      -  concatenate AOs into a row vector.
%   <a href="matlab:help ao/cdfplot">ao/cdfplot</a>                  -  makes cumulative distribution plot
%   <a href="matlab:help ao/cgfill">ao/cgfill</a>                   -  fills specified gaps in the data given an inital guess for the spectrum.
%   <a href="matlab:help ao/char">ao/char</a>                     -  overloads char() function for analysis objects.
%   <a href="matlab:help ao/checkDataType">ao/checkDataType</a>            -  Throws an error for AOs with a specified data-type.
%   <a href="matlab:help ao/checkNumericDataTypes">ao/checkNumericDataTypes</a>    -  Throws an error for AOs if the numeric data types doesn't match to an AO method.
%   <a href="matlab:help ao/checkTimestamps">ao/checkTimestamps</a>          -  performs a check on the timestamps of the input AOs.
%   <a href="matlab:help ao/clearErrors">ao/clearErrors</a>              - % Set units
%   <a href="matlab:help ao/cohere">ao/cohere</a>                   -  estimates the coherence between time-series objects
%   <a href="matlab:help ao/complex">ao/complex</a>                  -  overloads the complex operator for Analysis objects.
%   <a href="matlab:help ao/compute">ao/compute</a>                  -  performs the given operations on the input AOs.
%   <a href="matlab:help ao/computeDFT">ao/computeDFT</a>               -  Computes DFT using FFT or Goertzel
%   <a href="matlab:help ao/computeperiodogram">ao/computeperiodogram</a>       -    Periodogram spectral estimation.
%   <a href="matlab:help ao/confint">ao/confint</a>                  -  Calculates confidence levels and variance for psd, lpsd, cohere, lcohere and curvefit parameters
%   <a href="matlab:help ao/conj">ao/conj</a>                     -  overloads the conjugate operator for analysis objects.
%   <a href="matlab:help ao/consolidate">ao/consolidate</a>              -  resamples all input AOs onto the same time grid.
%   <a href="matlab:help ao/conv">ao/conv</a>                     -  vector convolution.
%   <a href="matlab:help ao/conv_noisegen">ao/conv_noisegen</a>            -  calls the matlab function conv.m to convolute poles and zeros from a given pzmodel
%   <a href="matlab:help ao/convert">ao/convert</a>                  -  perform various conversions on the ao.
%   <a href="matlab:help ao/copy">ao/copy</a>                     -  makes a (deep) copy of the input AOs.
%   <a href="matlab:help ao/corr">ao/corr</a>                     -  estimate linear correlation coefficients.
%   <a href="matlab:help ao/cos">ao/cos</a>                      -  overloads the cos method for analysis objects.
%   <a href="matlab:help ao/cov">ao/cov</a>                      -  estimate covariance of data streams.
%   <a href="matlab:help ao/cpsd">ao/cpsd</a>                     -  estimates the cross-spectral density between time-series objects
%   <a href="matlab:help ao/crb">ao/crb</a>                      -  computes the inverse of the Fisher Matrix
%   <a href="matlab:help ao/crbound">ao/crbound</a>                  -  computes the inverse of the Fisher Matrix
%   <a href="matlab:help ao/csvGenerateData">ao/csvGenerateData</a>          -  Default method to convert a analysis object into csv data.
%   <a href="matlab:help ao/ctranspose">ao/ctranspose</a>               -  overloads the ' operator for Analysis Objects.
%   <a href="matlab:help ao/cumsum">ao/cumsum</a>                   -  overloads the cumsum operator for analysis objects.
%   <a href="matlab:help ao/delay">ao/delay</a>                    -  delays a time-series using various methods.
%   <a href="matlab:help ao/delayEstimate">ao/delayEstimate</a>            -  estimates the delay between two AOs
%   <a href="matlab:help ao/delay_fractional_core">ao/delay_fractional_core</a>    -  core method to implement fractional delay
%   <a href="matlab:help ao/demux">ao/demux</a>                    -  splits the input vector of AOs into a number of output AOs.
%   <a href="matlab:help ao/det">ao/det</a>                      -  overloads the determinant function for analysis objects.
%   <a href="matlab:help ao/detectOutliers">ao/detectOutliers</a>           -  locates outliers in data.
%   <a href="matlab:help ao/detrend">ao/detrend</a>                  -  detrends the input analysis object using a polynomial of degree N.
%   <a href="matlab:help ao/dft">ao/dft</a>                      -  computes the DFT of the input time-series at the requested frequencies.
%   <a href="matlab:help ao/diag">ao/diag</a>                     -  overloads the diagonal operator for analysis objects.
%   <a href="matlab:help ao/diff">ao/diff</a>                     -  differentiates the data in AO.
%   <a href="matlab:help ao/diff2p_core">ao/diff2p_core</a>              - (No help available)
%   <a href="matlab:help ao/diff3p_core">ao/diff3p_core</a>              - (No help available)
%   <a href="matlab:help ao/diff5p_core">ao/diff5p_core</a>              - (No help available)
%   <a href="matlab:help ao/disp">ao/disp</a>                     -  implement terminal display for analysis object.
%   <a href="matlab:help ao/dispersionLoop">ao/dispersionLoop</a>           - dipersionLoop computes the dispersion function in loop
%   <a href="matlab:help ao/double">ao/double</a>                   -  overloads double() function for analysis objects.
%   <a href="matlab:help ao/downsample">ao/downsample</a>               -  decimate AOs by an integer factor.
%   <a href="matlab:help ao/dropduplicates">ao/dropduplicates</a>           -  drops all duplicate samples in time-series AOs.
%   <a href="matlab:help ao/dsmean">ao/dsmean</a>                   -  performs a simple downsampling by taking the mean of every N samples.
%   <a href="matlab:help ao/dtfe">ao/dtfe</a>                     -  estimates transfer function between time-series objects.
%   <a href="matlab:help ao/dx">ao/dx</a>                       -  Get the data property 'dx'.
%   <a href="matlab:help ao/dy">ao/dy</a>                       -  Get the data property 'dy'.
%   <a href="matlab:help ao/dz">ao/dz</a>                       - DX Get the data property 'dz'.
%   <a href="matlab:help ao/ecdf">ao/ecdf</a>                     -  calculate empirical cumulative distribution function
%   <a href="matlab:help ao/edgedetect">ao/edgedetect</a>               -  detects edges in a binary pulse-train.
%   <a href="matlab:help ao/eig">ao/eig</a>                      -  overloads the eigenvalues/eigenvectors function for analysis objects.
%   <a href="matlab:help ao/elementOp">ao/elementOp</a>                -  applies the given operator to the data.
%   <a href="matlab:help ao/eq">ao/eq</a>                       -  overloads == operator for analysis objects. Compare the y-axis values.
%   <a href="matlab:help ao/eqmotion">ao/eqmotion</a>                 -  solves numerically a given linear equation of motion
%   <a href="matlab:help ao/evaluateModel">ao/evaluateModel</a>            -  evaluate a curvefit model.
%   <a href="matlab:help ao/exp">ao/exp</a>                      -  overloads the exp operator for analysis objects. Exponential.
%   <a href="matlab:help ao/export">ao/export</a>                   -  export the data of an analysis object to a text file.
%   <a href="matlab:help ao/fft">ao/fft</a>                      -  overloads the fft method for Analysis objects.
%   <a href="matlab:help ao/fft_1sided_core">ao/fft_1sided_core</a>          - (No help available)
%   <a href="matlab:help ao/fft_2sided_core">ao/fft_2sided_core</a>          - (No help available)
%   <a href="matlab:help ao/fft_core">ao/fft_core</a>                 -  Simple core method which computes the fft.
%   <a href="matlab:help ao/fftfilt">ao/fftfilt</a>                  -  overrides the fft filter function for analysis objects.
%   <a href="matlab:help ao/fftfilt_core">ao/fftfilt_core</a>             -  Simple core method which computes the fft filter.
%   <a href="matlab:help ao/filtSubtract">ao/filtSubtract</a>             -  subtracts a frequency dependent noise contribution from an input ao.
%   <a href="matlab:help ao/filter">ao/filter</a>                   -  overrides the filter function for analysis objects.
%   <a href="matlab:help ao/filtfilt">ao/filtfilt</a>                 -  overrides the filtfilt function for analysis objects.
%   <a href="matlab:help ao/find">ao/find</a>                     -  particular samples that satisfy the input query and return a new AO.
%   <a href="matlab:help ao/findFsMax">ao/findFsMax</a>                -  Returns the max Fs of a set of AOs
%   <a href="matlab:help ao/findFsMin">ao/findFsMin</a>                -  Returns the min Fs of a set of AOs
%   <a href="matlab:help ao/findShortestVector">ao/findShortestVector</a>       -  Returns the length of the shortest vector in samples
%   <a href="matlab:help ao/firwhiten">ao/firwhiten</a>                -  whitens the input time-series by building an FIR whitening filter.
%   <a href="matlab:help ao/fixAxisData">ao/fixAxisData</a>              -  up the data type according to the users chosen axis
%   <a href="matlab:help ao/fixfs">ao/fixfs</a>                    -  resamples the input time-series to have a fixed sample rate.
%   <a href="matlab:help ao/flscov">ao/flscov</a>                   -  - Tool to perform a least square fit in frequency domain.
%   <a href="matlab:help ao/fngen">ao/fngen</a>                    -  creates an arbitrarily long time-series based on the input PSD.
%   <a href="matlab:help ao/fq2fac">ao/fq2fac</a>                   -  is a private function and is called by ngconv.m which can be found in the
%   <a href="matlab:help ao/fromComplexDatafile">ao/fromComplexDatafile</a>      -  Construct an AO from filename AND parameter list
%   <a href="matlab:help ao/fromDataInMAT">ao/fromDataInMAT</a>            -  Convert a saved data-array into an AO with a tsdata-object
%   <a href="matlab:help ao/fromDatafile">ao/fromDatafile</a>             -  Construct an ao from filename AND parameter list
%   <a href="matlab:help ao/fromDom">ao/fromDom</a>                  - % Get shape
%   <a href="matlab:help ao/fromFSfcn">ao/fromFSfcn</a>                -  Construct an ao from a fs-function string
%   <a href="matlab:help ao/fromFcn">ao/fromFcn</a>                  -  Construct an ao from a function string
%   <a href="matlab:help ao/fromParameter">ao/fromParameter</a>            -  Construct an ao from a param object
%   <a href="matlab:help ao/fromPest">ao/fromPest</a>                 -  Construct a AO from a pest.
%   <a href="matlab:help ao/fromPolyval">ao/fromPolyval</a>              -  Construct an ao from polynomial coefficients
%   <a href="matlab:help ao/fromProcinfo">ao/fromProcinfo</a>             -  returns for a given key-name the value of the procinfo-plist
%   <a href="matlab:help ao/fromPzmodel">ao/fromPzmodel</a>              -  Construct a time-series ao from polynomial coefficients
%   <a href="matlab:help ao/fromSModel">ao/fromSModel</a>               -  Construct a AO from an smodel.
%   <a href="matlab:help ao/fromSpecWin">ao/fromSpecWin</a>              -  Construct an ao from a Spectral window
%   <a href="matlab:help ao/fromStruct">ao/fromStruct</a>               -  creates from a structure an analysis object.
%   <a href="matlab:help ao/fromTSfcn">ao/fromTSfcn</a>                -  Construct an ao from a ts-function string
%   <a href="matlab:help ao/fromVals">ao/fromVals</a>                 -  Construct an ao from a value set
%   <a href="matlab:help ao/fromWaveform">ao/fromWaveform</a>             -  Construct an ao from a waveform
%   <a href="matlab:help ao/fromXYFcn">ao/fromXYFcn</a>                -  Construct an ao from a function f(x) string
%   <a href="matlab:help ao/fromXYVals">ao/fromXYVals</a>               -  Construct an ao from a value set
%   <a href="matlab:help ao/fromXYZVals">ao/fromXYZVals</a>              -  Construct an ao from a value set
%   <a href="matlab:help ao/fs">ao/fs</a>                       -  Get the data property 'fs'.
%   <a href="matlab:help ao/gapfilling">ao/gapfilling</a>               -  fills possible gaps in data.
%   <a href="matlab:help ao/gapfillingoptim">ao/gapfillingoptim</a>          -  fills possible gaps in data.
%   <a href="matlab:help ao/ge">ao/ge</a>                       -  overloads >= operator for analysis objects. Compare the y-axis values.
%   <a href="matlab:help ao/generateConstructorPlist">ao/generateConstructorPlist</a> -  generates a PLIST from the properties which can rebuild the object.
%   <a href="matlab:help ao/getAbsTimeRange">ao/getAbsTimeRange</a>          -  returns a timespan object which span the absolute time range of an AO
%   <a href="matlab:help ao/getCommonInterval">ao/getCommonInterval</a>        -  Estimates the common interval spun by a group of Analysis Objects
%   <a href="matlab:help ao/getGeneralInterval">ao/getGeneralInterval</a>       -  Estimates the maximum interval spun by a group of Analysis Objects
%   <a href="matlab:help ao/getKSCValPSD">ao/getKSCValPSD</a>             -  provides critical value for KStest on the PSD
%   <a href="matlab:help ao/getdof">ao/getdof</a>                   -  Calculates degrees of freedom for psd, lpsd, cohere and lcohere
%   <a href="matlab:help ao/gnuplot">ao/gnuplot</a>                  -  a gnuplot interface for AOs.
%   <a href="matlab:help ao/gt">ao/gt</a>                       -  overloads > operator for analysis objects. Compare the y-axis values.
%   <a href="matlab:help ao/heterodyne">ao/heterodyne</a>               -  heterodynes time-series.
%   <a href="matlab:help ao/highpass">ao/highpass</a>                 -  highpass AOs containing time-series data.
%   <a href="matlab:help ao/hist">ao/hist</a>                     -  overloads the histogram function (hist) of MATLAB for Analysis Objects.
%   <a href="matlab:help ao/hypot">ao/hypot</a>                    -  overloads robust computation of the square root of the sum of squares for AOs.
%   <a href="matlab:help ao/iacf">ao/iacf</a>                     -  computes the inverse auto-correlation function from a spectrum.
%   <a href="matlab:help ao/ifft">ao/ifft</a>                     -  overloads the ifft operator for Analysis objects.
%   <a href="matlab:help ao/ifft_1sided_even_core">ao/ifft_1sided_even_core</a>    - (No help available)
%   <a href="matlab:help ao/ifft_1sided_odd_core">ao/ifft_1sided_odd_core</a>     - (No help available)
%   <a href="matlab:help ao/ifft_2sided_core">ao/ifft_2sided_core</a>         - (No help available)
%   <a href="matlab:help ao/ifft_core">ao/ifft_core</a>                -  Simple core method which computes the ifft.
%   <a href="matlab:help ao/ifft_plain_core">ao/ifft_plain_core</a>          - (No help available)
%   <a href="matlab:help ao/imag">ao/imag</a>                     -  overloads the imaginary operator for analysis objects.
%   <a href="matlab:help ao/integrate">ao/integrate</a>                -  integrates the data in AO.
%   <a href="matlab:help ao/interp">ao/interp</a>                   -  interpolate the values in the input AO(s) at new values.
%   <a href="matlab:help ao/interpmissing">ao/interpmissing</a>            -  interpolate missing samples in a time-series.
%   <a href="matlab:help ao/intersect">ao/intersect</a>                -  overloads the intersect operator for Analysis objects.
%   <a href="matlab:help ao/inv">ao/inv</a>                      -  overloads the inverse function for analysis objects.
%   <a href="matlab:help ao/iplot">ao/iplot</a>                    -  provides an intelligent plotting tool for LTPDA.
%   <a href="matlab:help ao/iplotyy">ao/iplotyy</a>                  -  provides an intelligent plotting tool for LTPDA.
%   <a href="matlab:help ao/join">ao/join</a>                     -  multiple AOs into a single AO.
%   <a href="matlab:help ao/kstest">ao/kstest</a>                   -  perform KS test on input AOs
%   <a href="matlab:help ao/lcohere">ao/lcohere</a>                  -  implement magnitude-squadred coherence estimation on a log frequency axis.
%   <a href="matlab:help ao/lcpsd">ao/lcpsd</a>                    -  implement cross-power-spectral density estimation on a log frequency axis.
%   <a href="matlab:help ao/le">ao/le</a>                       -  overloads <= operator for analysis objects. Compare the y-axis values.
%   <a href="matlab:help ao/len">ao/len</a>                      -  overloads the length operator for Analysis objects. Length of the data samples.
%   <a href="matlab:help ao/linSubtract">ao/linSubtract</a>              -  subtracts a linear contribution from an input ao.
%   <a href="matlab:help ao/lincom">ao/lincom</a>                   -  make a linear combination of analysis objects
%   <a href="matlab:help ao/linedetect">ao/linedetect</a>               -  find spectral lines in the ao/fsdata objects.
%   <a href="matlab:help ao/linfit">ao/linfit</a>                   -  is a linear fitting tool
%   <a href="matlab:help ao/linlsqsvd">ao/linlsqsvd</a>                -  Linear least squares with singular value decomposition
%   <a href="matlab:help ao/lisovfit">ao/lisovfit</a>                 -  uses LISO to fit a pole/zero model to the input frequency-series.
%   <a href="matlab:help ao/ln">ao/ln</a>                       -  overloads the log operator for analysis objects. Natural logarithm.
%   <a href="matlab:help ao/loadobj">ao/loadobj</a>                  -  is called by the load function for user objects.
%   <a href="matlab:help ao/log">ao/log</a>                      -  overloads the log operator for analysis objects. Natural logarithm.
%   <a href="matlab:help ao/log10">ao/log10</a>                    -  overloads the log10 operator for analysis objects. Common (base 10) logarithm.
%   <a href="matlab:help ao/logical">ao/logical</a>                  -  overloads logical() function for analysis objects.
%   <a href="matlab:help ao/lowpass">ao/lowpass</a>                  -  lowpass AOs containing time-series data.
%   <a href="matlab:help ao/lpsd">ao/lpsd</a>                     -  implements the LPSD algorithm for analysis objects.
%   <a href="matlab:help ao/lscov">ao/lscov</a>                    -  is a wrapper for MATLAB's lscov function.
%   <a href="matlab:help ao/lsf">ao/lsf</a>                      - --------------------------------------------------------------------------
%   <a href="matlab:help ao/lt">ao/lt</a>                       -  overloads < operator for analysis objects. Compare the y-axis values.
%   <a href="matlab:help ao/ltf_plan">ao/ltf_plan</a>                 -  computes all input values needed for the LPSD and LTFE algorithms.
%   <a href="matlab:help ao/ltfe">ao/ltfe</a>                     -  implements transfer function estimation computed on a log frequency axis.
%   <a href="matlab:help ao/lxspec">ao/lxspec</a>                   -  performs log-scale cross-spectral analysis of various forms.
%   <a href="matlab:help ao/map3D">ao/map3D</a>                    -  maps the input 1 or 2D AOs on to a 3D AO
%   <a href="matlab:help ao/max">ao/max</a>                      -  computes the maximum value of the data in the AO
%   <a href="matlab:help ao/mchol">ao/mchol</a>                    - (No help available)
%   <a href="matlab:help ao/mcmc">ao/mcmc</a>                     -  estimates paramters using a Monte Carlo Markov Chain.
%   <a href="matlab:help ao/md5">ao/md5</a>                      -  computes an MD5 checksum from an analysis objects.
%   <a href="matlab:help ao/mean">ao/mean</a>                     -  computes the mean value of the data in the AO.
%   <a href="matlab:help ao/median">ao/median</a>                   -  computes the median value of the data in the AO.
%   <a href="matlab:help ao/melementOp">ao/melementOp</a>               -  applies the given matrix operator to the data.
%   <a href="matlab:help ao/min">ao/min</a>                      -  computes the minimum value of the data in the AO
%   <a href="matlab:help ao/minus">ao/minus</a>                    -  implements subtraction operator for analysis objects.
%   <a href="matlab:help ao/mlpsd_m">ao/mlpsd_m</a>                  -  m-file only version of the LPSD algorithm
%   <a href="matlab:help ao/mlpsd_mex">ao/mlpsd_mex</a>                -  calls the ltpda_dft.mex to compute the DFT part of the LPSD algorithm
%   <a href="matlab:help ao/mltfe">ao/mltfe</a>                    -  compute log-frequency space TF
%   <a href="matlab:help ao/mod">ao/mod</a>                      -  overloads the modulus function for analysis objects.
%   <a href="matlab:help ao/mode">ao/mode</a>                     -  computes the modal value of the data in the AO.
%   <a href="matlab:help ao/modelSelect">ao/modelSelect</a>              -  method to compute the Bayes Factor using RJMCMC, LF, LM, BIC methods
%   <a href="matlab:help ao/mpower">ao/mpower</a>                   -  implements mpower operator for analysis objects.
%   <a href="matlab:help ao/mrdivide">ao/mrdivide</a>                 -  implements mrdivide operator for analysis objects.
%   <a href="matlab:help ao/mtimes">ao/mtimes</a>                   -  implements mtimes operator for analysis objects.
%   <a href="matlab:help ao/mve">ao/mve</a>                      - MVE: Minimum Volume Ellipsoid estimator
%   <a href="matlab:help ao/ne">ao/ne</a>                       -  overloads ~= operator for analysis objects. Compare the y-axis values.
%   <a href="matlab:help ao/ngconv">ao/ngconv</a>                   -  is called by the function fromPzmodel
%   <a href="matlab:help ao/nginit">ao/nginit</a>                   -  is called by the function fromPzmodel
%   <a href="matlab:help ao/ngprop">ao/ngprop</a>                   -  is called by the function fromPzmodel
%   <a href="matlab:help ao/ngsetup">ao/ngsetup</a>                  -  is called by the function fromPzmodel
%   <a href="matlab:help ao/ngsetup_vpa">ao/ngsetup_vpa</a>              - % ALGONAME = mfilename;
%   <a href="matlab:help ao/noisePower">ao/noisePower</a>               -  computes the noise power spectral density in a time-series as a function of time.
%   <a href="matlab:help ao/noisegen1D">ao/noisegen1D</a>               -  generates colored noise from white noise.
%   <a href="matlab:help ao/noisegen2D">ao/noisegen2D</a>               -  generates cross correleted colored noise from white noise.
%   <a href="matlab:help ao/norm">ao/norm</a>                     -  overloads the norm operator for analysis objects.
%   <a href="matlab:help ao/normdist">ao/normdist</a>                 -  computes the equivalent normal distribution for the data.
%   <a href="matlab:help ao/not">ao/not</a>                      -  overloads the logical not operator for analysis objects.
%   <a href="matlab:help ao/nsecs">ao/nsecs</a>                    -  Get the data property 'nsecs'.
%   <a href="matlab:help ao/nyquistplot">ao/nyquistplot</a>              -  fits a piecewise powerlaw to the given data.
%   <a href="matlab:help ao/offset">ao/offset</a>                   -  adds an offset to the data in the AO.
%   <a href="matlab:help ao/or">ao/or</a>                       -  (|) overloads the or (|) method for Analysis objects.
%   <a href="matlab:help ao/overlap">ao/overlap</a>                  -  This method cuts out the the overlapping data of the input AOs.
%   <a href="matlab:help ao/pad">ao/pad</a>                      -  pads the input data series to a given value.
%   <a href="matlab:help ao/performFFTcore">ao/performFFTcore</a>           -  performs fft for flscov and flscovSegments
%   <a href="matlab:help ao/phase">ao/phase</a>                    -  is the phase operator for analysis objects.
%   <a href="matlab:help ao/play">ao/play</a>                     -  plays a time-series using MATLAB's audioplay function.
%   <a href="matlab:help ao/plot">ao/plot</a>                     -  the analysis objects on the given axes.
%   <a href="matlab:help ao/plus">ao/plus</a>                     -  implements addition operator for analysis objects.
%   <a href="matlab:help ao/polyfit">ao/polyfit</a>                  -  overloads polyfit() function of MATLAB for Analysis Objects.
%   <a href="matlab:help ao/polyfitSpectrum">ao/polyfitSpectrum</a>          -  does a polynomial fit to the log of the input spectrum.
%   <a href="matlab:help ao/polynomfit">ao/polynomfit</a>               -  is a polynomial fitting tool
%   <a href="matlab:help ao/power">ao/power</a>                    -  implements power operator for analysis objects.
%   <a href="matlab:help ao/powerFit">ao/powerFit</a>                 -  fits a piecewise powerlaw to the given data.
%   <a href="matlab:help ao/ppsd">ao/ppsd</a>                     -  makes power spectral density estimates of the time-series objects in the input analysis objects by estimating ARMA models coefficients.
%   <a href="matlab:help ao/preprocessDataForMCMC">ao/preprocessDataForMCMC</a>    -  Split, resample and apply FFT to time series for MCMC analysis.
%   <a href="matlab:help ao/processSetterValues">ao/processSetterValues</a>      - (No help available)
%   <a href="matlab:help ao/psd">ao/psd</a>                      -  makes power spectral density estimates of the time-series objects
%   <a href="matlab:help ao/psdconf">ao/psdconf</a>                  -  Calculates confidence levels and variance for psd
%   <a href="matlab:help ao/psdvfit">ao/psdvfit</a>                  -  performs a fitting loop to identify model for a psd.
%   <a href="matlab:help ao/qqplot">ao/qqplot</a>                   -  makes quantile-quantile plot
%   <a href="matlab:help ao/quasiSweptSine">ao/quasiSweptSine</a>           -  computes a transfer function from swept-sine measurements
%   <a href="matlab:help ao/rdivide">ao/rdivide</a>                  -  implements division operator for analysis objects.
%   <a href="matlab:help ao/real">ao/real</a>                     -  overloads the real operator for analysis objects.
%   <a href="matlab:help ao/removeVal">ao/removeVal</a>                -  removes values from the input AO(s).
%   <a href="matlab:help ao/resample">ao/resample</a>                 -  overloads resample function for AOs.
%   <a href="matlab:help ao/resampleToCommonGrid">ao/resampleToCommonGrid</a>     -  Resamples Analysis Objects to a common grid
%   <a href="matlab:help ao/rjsample">ao/rjsample</a>                 -  Reverse Jump MCMC sampling using the "Metropolized Carlin And Chib" Method.
%   <a href="matlab:help ao/rms">ao/rms</a>                      -  Calculate RMS deviation from spectrum
%   <a href="matlab:help ao/rotate">ao/rotate</a>                   -  applies rotation factor to AOs
%   <a href="matlab:help ao/round">ao/round</a>                    -  overloads the Round method for analysis objects.
%   <a href="matlab:help ao/sDomainFit">ao/sDomainFit</a>               -  performs a fitting loop to identify model order and
%   <a href="matlab:help ao/scale">ao/scale</a>                    -  scales the data in the AO by the specified factor.
%   <a href="matlab:help ao/scatter3D">ao/scatter3D</a>                -  Creates from the y-values of the input AOs a new AO with a xyz-data object
%   <a href="matlab:help ao/scatterData">ao/scatterData</a>              -  Creates from the y-values of two input AOs an new AO(xydata)
%   <a href="matlab:help ao/select">ao/select</a>                   -  select particular samples from the input AOs and return new AOs with only those samples.
%   <a href="matlab:help ao/setData">ao/setData</a>                  -  sets the 'data' property of the ao.
%   <a href="matlab:help ao/setDx">ao/setDx</a>                    -  sets the 'dx' property of the ao.
%   <a href="matlab:help ao/setDy">ao/setDy</a>                    -  sets the 'dy' property of the ao.
%   <a href="matlab:help ao/setDz">ao/setDz</a>                    -  sets the 'dz' property of the ao.
%   <a href="matlab:help ao/setEnbw">ao/setEnbw</a>                  -  sets the 'enbw' property of the ao/fsdata.
%   <a href="matlab:help ao/setFs">ao/setFs</a>                    -  sets the 'fs' property of the ao.
%   <a href="matlab:help ao/setNavs">ao/setNavs</a>                  -  sets the 'navs' property of the ao/fsdata.
%   <a href="matlab:help ao/setReferenceTime">ao/setReferenceTime</a>         -  sets the t0 to the new value but doesn't move the data in time
%   <a href="matlab:help ao/setT0">ao/setT0</a>                    -  sets the 't0' property of the ao.
%   <a href="matlab:help ao/setToffset">ao/setToffset</a>               -  sets the 'toffset' property of the ao with tsdata
%   <a href="matlab:help ao/setUnitsForAxis">ao/setUnitsForAxis</a>          - % Set units
%   <a href="matlab:help ao/setX">ao/setX</a>                     -  sets the 'x' property of the ao.
%   <a href="matlab:help ao/setXY">ao/setXY</a>                    -  sets the 'x' and 'y' properties of the ao.
%   <a href="matlab:help ao/setXaxisName">ao/setXaxisName</a>             -  sets the x-axis name of the ao.
%   <a href="matlab:help ao/setXunits">ao/setXunits</a>                -  sets the 'xunits' property of the ao.
%   <a href="matlab:help ao/setY">ao/setY</a>                     -  sets the 'y' property of the ao.
%   <a href="matlab:help ao/setYaxisName">ao/setYaxisName</a>             -  sets the y-axis name of the ao.
%   <a href="matlab:help ao/setYunits">ao/setYunits</a>                -  sets the 'yunits' property of the ao.
%   <a href="matlab:help ao/setZ">ao/setZ</a>                     -  sets the 'z' property of the ao.
%   <a href="matlab:help ao/setZaxisName">ao/setZaxisName</a>             -  sets the z-axis name of the ao.
%   <a href="matlab:help ao/setZunits">ao/setZunits</a>                -  sets the 'zunits' property of the ao.
%   <a href="matlab:help ao/sign">ao/sign</a>                     -  overloads the sign operator for analysis objects.
%   <a href="matlab:help ao/simplex">ao/simplex</a>                  -  Multidimensional unconstrained nonlinear minimization (Nelder-Mead)
%   <a href="matlab:help ao/simplifyXunits">ao/simplifyXunits</a>           -  simplify the 'xunits' of the ao.
%   <a href="matlab:help ao/simplifyYunits">ao/simplifyYunits</a>           -  simplify the 'yunits' property of the ao.
%   <a href="matlab:help ao/simplifyZunits">ao/simplifyZunits</a>           -  simplify the 'zunits' of the ao.
%   <a href="matlab:help ao/sin">ao/sin</a>                      -  overloads the sin method for analysis objects.
%   <a href="matlab:help ao/sineParams">ao/sineParams</a>               -  estimates parameters of sinusoids
%   <a href="matlab:help ao/smoother">ao/smoother</a>                 -  smooths a given series of data points using the specified method.
%   <a href="matlab:help ao/sort">ao/sort</a>                     -  the values in the AO.
%   <a href="matlab:help ao/spcorr">ao/spcorr</a>                   -  calculate Spearman Rank-Order Correlation Coefficient
%   <a href="matlab:help ao/spectrogram">ao/spectrogram</a>              -  computes a spectrogram of the given ao/tsdata.
%   <a href="matlab:help ao/spikecleaning">ao/spikecleaning</a>            -  detects and corrects possible spikes in analysis objects
%   <a href="matlab:help ao/split">ao/split</a>                    -  split an analysis object into the specified segments.
%   <a href="matlab:help ao/split_samples_core">ao/split_samples_core</a>       - (No help available)
%   <a href="matlab:help ao/spsd">ao/spsd</a>                     -  implements the smoothed (binned) PSD algorithm for analysis objects.
%   <a href="matlab:help ao/spsdSubtraction">ao/spsdSubtraction</a>          -  makes a sPSD-weighted least-square iterative fit
%   <a href="matlab:help ao/sqrt">ao/sqrt</a>                     -  computes the square root of the data in the AO.
%   <a href="matlab:help ao/stack">ao/stack</a>                    -  xydata.
%   <a href="matlab:help ao/std">ao/std</a>                      -  computes the standard deviation of the data in the AO.
%   <a href="matlab:help ao/subsData">ao/subsData</a>                 -  performs actions on ao objects.
%   <a href="matlab:help ao/sum">ao/sum</a>                      -  computes the sum of the data in the AO.
%   <a href="matlab:help ao/sumjoin">ao/sumjoin</a>                  -  sums time-series signals togther
%   <a href="matlab:help ao/summaryReport">ao/summaryReport</a>            -  generates an HTML report about the input objects.
%   <a href="matlab:help ao/svd">ao/svd</a>                      -  overloads the svd (singular value decomposition) function for analysis objects.
%   <a href="matlab:help ao/svd_fit">ao/svd_fit</a>                  -  estimates parameters for a linear model using SVD
%   <a href="matlab:help ao/t0">ao/t0</a>                       -  Get the data property 't0'.
%   <a href="matlab:help ao/table">ao/table</a>                    -  display the data from the AO in a table.
%   <a href="matlab:help ao/tan">ao/tan</a>                      -  overloads the tan method for analysis objects.
%   <a href="matlab:help ao/tdfit">ao/tdfit</a>                    -  fit a set of smodels to a set of input and output signals..
%   <a href="matlab:help ao/tfe">ao/tfe</a>                      -  estimates transfer function between time-series objects.
%   <a href="matlab:help ao/timeaverage">ao/timeaverage</a>              -  Averages time series intervals
%   <a href="matlab:help ao/times">ao/times</a>                    -  implements multiplication operator for analysis objects.
%   <a href="matlab:help ao/timeshift">ao/timeshift</a>                -  for AO/tsdata objects, shifts data in time by the specified value in seconds.
%   <a href="matlab:help ao/toSI">ao/toSI</a>                     -  converts the units of the x, y and z axes into SI units.
%   <a href="matlab:help ao/toffset">ao/toffset</a>                  -  Get the data property 'toffset'.
%   <a href="matlab:help ao/transpose">ao/transpose</a>                -  overloads the .' operator for Analysis Objects.
%   <a href="matlab:help ao/trends">ao/trends</a>                   -  computes the trend statistics of the input time-series.
%   <a href="matlab:help ao/truncate">ao/truncate</a>                 -  Splits Analysis Objects over a common timespan
%   <a href="matlab:help ao/uminus">ao/uminus</a>                   -  overloads the uminus operator for analysis objects.
%   <a href="matlab:help ao/union">ao/union</a>                    -  overloads the union operator for Analysis Objects.
%   <a href="matlab:help ao/unwrap">ao/unwrap</a>                   -  overloads the unwrap operator for analysis objects.
%   <a href="matlab:help ao/update_struct">ao/update_struct</a>            -  update the input structure to the current ltpda version
%   <a href="matlab:help ao/upsample">ao/upsample</a>                 -  overloads upsample function for AOs.
%   <a href="matlab:help ao/validate">ao/validate</a>                 -  checks that the input Analysis Object is reproducible and valid.
%   <a href="matlab:help ao/validateSpectrumMod">ao/validateSpectrumMod</a>      -  statistically validate a model for a psd.
%   <a href="matlab:help ao/var">ao/var</a>                      -  computes the variance of the data in the AO.
%   <a href="matlab:help ao/whiten1D">ao/whiten1D</a>                 -  whitens the input time-series.
%   <a href="matlab:help ao/whiten2D">ao/whiten2D</a>                 -  whiten the noise for two cross correlated time series.
%   <a href="matlab:help ao/window">ao/window</a>                   -  applies the specified window to the input time-series objects
%   <a href="matlab:help ao/wosa">ao/wosa</a>                     -  implements Welch's overlaped segmented averaging algorithm with
%   <a href="matlab:help ao/x">ao/x</a>                        -  Get the data property 'x'.
%   <a href="matlab:help ao/xaxisname">ao/xaxisname</a>                -  Get the x axis name of the underlying data object.
%   <a href="matlab:help ao/xcorr">ao/xcorr</a>                    -  makes cross-correlation estimates of the time-series
%   <a href="matlab:help ao/xfit">ao/xfit</a>                     -  fit a function of x to data.
%   <a href="matlab:help ao/xor">ao/xor</a>                      -  overloads the xor (exclusive or) method for Analysis objects.
%   <a href="matlab:help ao/xspec">ao/xspec</a>                    -  performs cross-spectral analysis of various forms.
%   <a href="matlab:help ao/xunits">ao/xunits</a>                   -  Get the data property 'xunits'.
%   <a href="matlab:help ao/y">ao/y</a>                        -  Get the data property 'y'.
%   <a href="matlab:help ao/yaxisname">ao/yaxisname</a>                -  Get the y axis name of the underlying data object.
%   <a href="matlab:help ao/yunits">ao/yunits</a>                   -  Get the data property 'yunits'.
%   <a href="matlab:help ao/z">ao/z</a>                        -  Get the data property 'z'.
%   <a href="matlab:help ao/zDomainFit">ao/zDomainFit</a>               -  performs a fitting loop to identify model order and
%   <a href="matlab:help ao/zaxisname">ao/zaxisname</a>                -  Get the z axis name of the underlying data object.
%   <a href="matlab:help ao/zeropad">ao/zeropad</a>                  -  zero pads the input data series.
%   <a href="matlab:help ao/zeropad_post_core">ao/zeropad_post_core</a>        - (No help available)
%   <a href="matlab:help ao/zunits">ao/zunits</a>                   -  Get the data property 'zunits'.
