% LTPDA_NON_ABSTRACT_CLASSES lists all non abstract LTPDA object classes.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% DESCRIPTION: LTPDA_CLASSES lists all non abstract LTPDA object classes.
%
% CALL:        classes = ltpda_non_abstract_classes()
%
% OUTPUTS:     classes - a cell array with a list of recognised LTPDA object types
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function classes = ltpda_non_abstract_classes()
  
  % Building the array is faster than caching with persistent.
  classes = {...
    ...% Not user classes
    'history', ...
    'minfo', ...
    'msym', ...
    'param', ...
    'paramValue', ...
    'plotinfo', ...
    'provenance', ...
    'pz', ...
    'specwin', ...
    'ssmport', ...
    'ssmblock', ...
    'time', ...
    'unit', ...
    ...
    'cdata', ...
    'tsdata', ...
    'fsdata', ...
    'xydata', ...
    'xyzdata', ...
    'tfmap', ...
    ...
    ...% LTPDA user classes
    'MCMC', ...
    'ao', ...
    'collection', ...
    'filterbank', ...
    'matrix', ...
    'mfh', ...
    'mfir', ...
    'miir', ...
    'parfrac', ...
    'pest', ...
    'plist', ...
    'pzmodel', ...
    'rational', ...
    'smodel', ...
    'ssm', ...
    'timespan', ...
    };
  
end

