% LTPDA_CLASSES lists all the LTPDA object types.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% DESCRIPTION: LTPDA_CLASSES lists all the LTPDA object types.
%
% CALL:        classes = ltpda_classes()
%
% INPUTS:
%
% OUTPUTS:     classes - a cell array with a list of recognised LTPDA object types
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function classes = ltpda_classes(varargin)
  
  % Building the array is faster than caching with persistent.
  classes = {...
    ...% LTPDA user classes
    'ao', ...
    'collection', ...
    'filterbank', ...
    'matrix', ...
    'mfh', ...
    'mfir', ...
    'miir', ...
    'parfrac', ...
    'pest', ...
    'plist', ...
    'pzmodel', ...
    'rational', ...
    'smodel', ...
    'ssm', ...
    'timespan', ...
    'MCMC', ...
    'LTPDANamedItem', ...
    ... % Abstract or Hidden classes
    'ltpda_obj', ...
    'ltpda_uo',  ...
    'ltpda_uoh', ...
    'ltpda_filter', ...
    'ltpda_tf', ...
    'ltpda_container', ...
    'ltpda_algorithm', ...
    ...
    'ltpda_nuo', ...
    'ltpda_vector', ...
    'ltpda_data', ...
    'data2D', ...
    'data3D', ...
    ...
    ...% Not user classes
    'history', ...
    'minfo', ...
    'msym', ...
    'param', ...
    'paramValue', ...
    'plotinfo', ...
    'provenance', ...
    'pz', ...
    'specwin', ...
    'ssmport', ...
    'ssmblock', ...
    'time', ...
    'unit', ...
    ...
    'cdata', ...
    'tsdata', ...
    'fsdata', ...
    'xydata', ...
    'xyzdata', ...
    'tfmap', ...
    ...
    };
  
end

