%%%%%%%%%%%%%%%%%%%%   path: examples   %%%%%%%%%%%%%%%%%%%%
%
%   <a href="matlab:help examples/ao_class_test">examples/ao_class_test</a>           - % AO_CLASS_TEST Test analysis object class
%   <a href="matlab:help examples/example_1">examples/example_1</a>               -  A test script for the AO implementation.
%   <a href="matlab:help examples/example_2">examples/example_2</a>               -  test script for the AO implementation.
%   <a href="matlab:help examples/make_test_ascii_file">examples/make_test_ascii_file</a>    -  a test ascii file with the name 'name.txt' containing a time-series
%   <a href="matlab:help examples/run_tests">examples/run_tests</a>               -  many tests
%   <a href="matlab:help examples/test_LTPDAprefs_cl_set">examples/test_LTPDAprefs_cl_set</a>  - Check that direct setting of LTPDA preferences is working.
%   <a href="matlab:help examples/test_abs">examples/test_abs</a>                -  abs() operator for AOs.
%   <a href="matlab:help examples/test_acos">examples/test_acos</a>               -  test acos() operator for analysis objects.
%   <a href="matlab:help examples/test_ao_1">examples/test_ao_1</a>               -  functionality of analysis objects.
%   <a href="matlab:help examples/test_ao_bilinfit">examples/test_ao_bilinfit</a>        -  ao/bilinfit for:
%   <a href="matlab:help examples/test_ao_cohere">examples/test_ao_cohere</a>          -  ao.cohere functionality.
%   <a href="matlab:help examples/test_ao_consolidate">examples/test_ao_consolidate</a>     -  tests the consolidate method of the AO class.
%   <a href="matlab:help examples/test_ao_cov">examples/test_ao_cov</a>             -  test cov() operator for analysis objects.
%   <a href="matlab:help examples/test_ao_cpsd">examples/test_ao_cpsd</a>            -  ao.cpsd functionality.
%   <a href="matlab:help examples/test_ao_detrend">examples/test_ao_detrend</a>         -  tests the detrend method of the AO class.
%   <a href="matlab:help examples/test_ao_downsample">examples/test_ao_downsample</a>      -  tests downsample method of AO class.
%   <a href="matlab:help examples/test_ao_fftfilt">examples/test_ao_fftfilt</a>         -  script for ao/fftfilt
%   <a href="matlab:help examples/test_ao_find">examples/test_ao_find</a>            -  test the find function of AO class.
%   <a href="matlab:help examples/test_ao_freq_series">examples/test_ao_freq_series</a>     - % Test script for frequency series AO constructor
%   <a href="matlab:help examples/test_ao_fromVals">examples/test_ao_fromVals</a>        -  construct AOs in different ways
%   <a href="matlab:help examples/test_ao_gapfilling">examples/test_ao_gapfilling</a>      -  test script for the ao.gapfilling method
%   <a href="matlab:help examples/test_ao_heterodyne">examples/test_ao_heterodyne</a>      - Tests for ao/heterodyne
%   <a href="matlab:help examples/test_ao_hist">examples/test_ao_hist</a>            -  tests the histogram function of the AO class.
%   <a href="matlab:help examples/test_ao_interp">examples/test_ao_interp</a>          -  tests the interp method of AO class.
%   <a href="matlab:help examples/test_ao_join_ts">examples/test_ao_join_ts</a>         -  test then join method of AO class for tsdata objects.
%   <a href="matlab:help examples/test_ao_lincom">examples/test_ao_lincom</a>          -  script for ao/lincom
%   <a href="matlab:help examples/test_ao_linedetect">examples/test_ao_linedetect</a>      - Tests for ao/linedetect
%   <a href="matlab:help examples/test_ao_linfit">examples/test_ao_linfit</a>          -  tests the linfit method of the AO class.
%   <a href="matlab:help examples/test_ao_lscov">examples/test_ao_lscov</a>           -  tests the lscov method of the AO class.
%   <a href="matlab:help examples/test_ao_plot">examples/test_ao_plot</a>            -  cases for ao/plot
%   <a href="matlab:help examples/test_ao_polyfit">examples/test_ao_polyfit</a>         -  tests the polyfit method of the AO class.
%   <a href="matlab:help examples/test_ao_pwelch">examples/test_ao_pwelch</a>          -  ao.pwelch functionality.
%   <a href="matlab:help examples/test_ao_removeVal">examples/test_ao_removeVal</a>       -  ao/removeVal for:
%   <a href="matlab:help examples/test_ao_rotate">examples/test_ao_rotate</a>          - % test the rotate method
%   <a href="matlab:help examples/test_ao_select">examples/test_ao_select</a>          -  test the select function of AO class.
%   <a href="matlab:help examples/test_ao_spikecleaning">examples/test_ao_spikecleaning</a>   -  test script for the spikecleaning method
%   <a href="matlab:help examples/test_ao_split">examples/test_ao_split</a>           -  AO split method.
%   <a href="matlab:help examples/test_ao_split_frequency">examples/test_ao_split_frequency</a> -  splitting a frequency-series AO by frequency using the split method.
%   <a href="matlab:help examples/test_ao_tfe">examples/test_ao_tfe</a>             -  ao.tfe functionality.
%   <a href="matlab:help examples/test_ao_timeaverage">examples/test_ao_timeaverage</a>     - % create a tsdata ao
%   <a href="matlab:help examples/test_ao_tsfcn">examples/test_ao_tsfcn</a>           -  AO constructor for TS function
%   <a href="matlab:help examples/test_ao_upsample">examples/test_ao_upsample</a>        -  tests upsample method of AO class.
%   <a href="matlab:help examples/test_ao_waveform">examples/test_ao_waveform</a>        -  test the waveform constructor for AO class.
%   <a href="matlab:help examples/test_ao_xfit">examples/test_ao_xfit</a>            - Tests for xfit
%   <a href="matlab:help examples/test_asin">examples/test_asin</a>               -  test asin() operator for analysis objects.
%   <a href="matlab:help examples/test_atan">examples/test_atan</a>               -  test atan() operator for analysis objects.
%   <a href="matlab:help examples/test_collection_history">examples/test_collection_history</a> - %%
%   <a href="matlab:help examples/test_collection_plot">examples/test_collection_plot</a>    - %% Plot 4 AOs
%   <a href="matlab:help examples/test_conj">examples/test_conj</a>               - Tests conj() operator for AOs.
%   <a href="matlab:help examples/test_cos">examples/test_cos</a>                -  test cos() operator for analysis objects.
%   <a href="matlab:help examples/test_ctranspose">examples/test_ctranspose</a>         -  ctranspose() operator for AOs.
%   <a href="matlab:help examples/test_det">examples/test_det</a>                -  ao.det method.
%   <a href="matlab:help examples/test_diag">examples/test_diag</a>               - Tests ao.diag method.
%   <a href="matlab:help examples/test_eig">examples/test_eig</a>                - Tests ao.eig method.
%   <a href="matlab:help examples/test_exp">examples/test_exp</a>                -  test exp() operator for analysis objects.
%   <a href="matlab:help examples/test_fft">examples/test_fft</a>                -  fft() operator for AOs.
%   <a href="matlab:help examples/test_filter_edges">examples/test_filter_edges</a>       -  tests if filter function correctly stores the state
%   <a href="matlab:help examples/test_fir_filter">examples/test_fir_filter</a>         -  test FIR filtering of AO class.
%   <a href="matlab:help examples/test_iir_filtering">examples/test_iir_filtering</a>      - A test script to test some IIR filtering commands.
%   <a href="matlab:help examples/test_inv">examples/test_inv</a>                - Tests ao.inv method.
%   <a href="matlab:help examples/test_iplot">examples/test_iplot</a>              -  test some aspects of iplot.
%   <a href="matlab:help examples/test_iplot_2">examples/test_iplot_2</a>            - %% When cdata contains a matrix
%   <a href="matlab:help examples/test_iplot_3">examples/test_iplot_3</a>            - Some iplot tests using the plotinfo
%   <a href="matlab:help examples/test_isequal">examples/test_isequal</a>            - %% This script test all parts of ltpda_obj/isequal
%   <a href="matlab:help examples/test_lincom_cdata">examples/test_lincom_cdata</a>       -  script for ao.lincom.
%   <a href="matlab:help examples/test_list">examples/test_list</a>               - A list of tests for running and installing in the toolbox as examples.
%   <a href="matlab:help examples/test_log10">examples/test_log10</a>              -  test log10() operator for analysis objects.
%   <a href="matlab:help examples/test_log_ln">examples/test_log_ln</a>             -  test log() operator for analysis objects.
%   <a href="matlab:help examples/test_lpsd">examples/test_lpsd</a>               - A test script for the AO implementation of lpsd.
%   <a href="matlab:help examples/test_ltpda_cohere">examples/test_ltpda_cohere</a>       -  ao.cohere functionality.
%   <a href="matlab:help examples/test_ltpda_cpsd">examples/test_ltpda_cpsd</a>         -  ao.cpsd functionality.
%   <a href="matlab:help examples/test_ltpda_lincom">examples/test_ltpda_lincom</a>       -  script for ao.lincom.
%   <a href="matlab:help examples/test_ltpda_linedetect">examples/test_ltpda_linedetect</a>   -  test script for ao.linedetect.
%   <a href="matlab:help examples/test_ltpda_ltfe">examples/test_ltpda_ltfe</a>         -  test the ao.ltfe method.
%   <a href="matlab:help examples/test_ltpda_nfest">examples/test_ltpda_nfest</a>        -  tests the ltpda_nfest noise-floor estimator.
%   <a href="matlab:help examples/test_ltpda_polydetrend">examples/test_ltpda_polydetrend</a>  -  script for ao.detrend
%   <a href="matlab:help examples/test_ltpda_pwelch">examples/test_ltpda_pwelch</a>       -  the LTPDA wrapping of pwelch.
%   <a href="matlab:help examples/test_ltpda_tfe">examples/test_ltpda_tfe</a>          -  ao.tfe functionality.
%   <a href="matlab:help examples/test_ltpda_xcorr">examples/test_ltpda_xcorr</a>        -  tests the cross-correlation function ltpda_xcorr.
%   <a href="matlab:help examples/test_matrix_plot">examples/test_matrix_plot</a>        - %% Plot 2x1
%   <a href="matlab:help examples/test_mean">examples/test_mean</a>               -  test mean() operator for analysis objects.
%   <a href="matlab:help examples/test_median">examples/test_median</a>             -  test median() operator for analysis objects.
%   <a href="matlab:help examples/test_mfir_class">examples/test_mfir_class</a>         -  tests run on mfir class.
%   <a href="matlab:help examples/test_miir_class">examples/test_miir_class</a>         -  the constructor for miir objects.
%   <a href="matlab:help examples/test_miir_filter">examples/test_miir_filter</a>        -  the ao/filter function for the miir class.
%   <a href="matlab:help examples/test_miir_filtfilt">examples/test_miir_filtfilt</a>      -  the filtfilt function for the miir class.
%   <a href="matlab:help examples/test_miir_redesign">examples/test_miir_redesign</a>      - When the filter command is given a standard filter designed for a
%   <a href="matlab:help examples/test_minus">examples/test_minus</a>              - A test script for the AO minus.
%   <a href="matlab:help examples/test_mpower">examples/test_mpower</a>             - A test script for the AO mpower.
%   <a href="matlab:help examples/test_norm">examples/test_norm</a>               -  ao.norm method.
%   <a href="matlab:help examples/test_plist_string">examples/test_plist_string</a>       - Tests string method of plist class.
%   <a href="matlab:help examples/test_plus">examples/test_plus</a>               - A test script for the AO plus.
%   <a href="matlab:help examples/test_pzm_to_fir">examples/test_pzm_to_fir</a>         -  tests converting pzmodel into an FIR filter
%   <a href="matlab:help examples/test_pzmodel_class">examples/test_pzmodel_class</a>      -  script for pzmodel class.
%   <a href="matlab:help examples/test_rdivide">examples/test_rdivide</a>            - A test script for the AO ./ .
%   <a href="matlab:help examples/test_recreate_1">examples/test_recreate_1</a>         - Testing features of 'recreate from history'.
%   <a href="matlab:help examples/test_resample">examples/test_resample</a>           -  resample function for AOs.
%   <a href="matlab:help examples/test_simulated_data">examples/test_simulated_data</a>     -  making simulated data AOs.
%   <a href="matlab:help examples/test_sin">examples/test_sin</a>                -  test sin() operator for analysis objects.
%   <a href="matlab:help examples/test_smodel_double">examples/test_smodel_double</a>      -  tests the double method of the SMODEL class.
%   <a href="matlab:help examples/test_smodel_eval">examples/test_smodel_eval</a>        -  tests the eval method of the SMODEL class.
%   <a href="matlab:help examples/test_sqrt">examples/test_sqrt</a>               -  test sqrt() operator for analysis objects.
%   <a href="matlab:help examples/test_std">examples/test_std</a>                -  test std() operator for analysis objects.
%   <a href="matlab:help examples/test_svd">examples/test_svd</a>                -  ao.svd method.
%   <a href="matlab:help examples/test_tan">examples/test_tan</a>                -  test tan() operator for analysis objects.
%   <a href="matlab:help examples/test_times">examples/test_times</a>              - A test script for the AO times.
%   <a href="matlab:help examples/test_transpose">examples/test_transpose</a>          -  transpose() operator for AOs.
%   <a href="matlab:help examples/test_tsdata_class">examples/test_tsdata_class</a>       -  script for tsdata class
%   <a href="matlab:help examples/test_var">examples/test_var</a>                -  test var() operator for analysis objects.
%   <a href="matlab:help examples/test_xml_complex">examples/test_xml_complex</a>        -  reading and writing complex data to XML file.
%   <a href="matlab:help examples/testing_xml">examples/testing_xml</a>             -  saving AO to xml
