%%%%%%%%%%%%%%%%%%%%   class: smodel   %%%%%%%%%%%%%%%%%%%%
%
%   <a href="matlab:help smodel/addAliases">smodel/addAliases</a>               -  Add the key-value pairs to the alias-names and alias-values
%   <a href="matlab:help smodel/addParameters">smodel/addParameters</a>            -  Add some parameters to the symbolic model (smodel) object
%   <a href="matlab:help smodel/assignalias">smodel/assignalias</a>              -  assign values to smodel alias
%   <a href="matlab:help smodel/attachToDom">smodel/attachToDom</a>              - % Create empty smodel node with the attribute 'shape'
%   <a href="matlab:help smodel/char">smodel/char</a>                     -  convert a smodel object into a string.
%   <a href="matlab:help smodel/clearAliases">smodel/clearAliases</a>             -  Clear the aliases.
%   <a href="matlab:help smodel/conj">smodel/conj</a>                     -  gives the complex conjugate of the input smodels
%   <a href="matlab:help smodel/convol_integral">smodel/convol_integral</a>          -  implements the convolution integral for smodel objects.
%   <a href="matlab:help smodel/copy">smodel/copy</a>                     -  makes a (deep) copy of the input smodel objects.
%   <a href="matlab:help smodel/det">smodel/det</a>                      -  evaluates the determinant of smodel objects.
%   <a href="matlab:help smodel/diff">smodel/diff</a>                     -  implements differentiation operator for smodel objects.
%   <a href="matlab:help smodel/disp">smodel/disp</a>                     -  overloads display functionality for smodel objects.
%   <a href="matlab:help smodel/double">smodel/double</a>                   -  Returns the numeric result of the model.
%   <a href="matlab:help smodel/elementOp">smodel/elementOp</a>                -  applies the given operator to the input smodels.
%   <a href="matlab:help smodel/eval">smodel/eval</a>                     -  evaluates the symbolic model and returns an AO containing the numeric data.
%   <a href="matlab:help smodel/fitfunc">smodel/fitfunc</a>                  -  Returns a function handle which sets the 'values' and 'xvals' to a ltpda model.
%   <a href="matlab:help smodel/fourier">smodel/fourier</a>                  -  implements continuous f-domain Fourier transform for smodel objects.
%   <a href="matlab:help smodel/fromDatafile">smodel/fromDatafile</a>             -  Construct smodel object from filename AND parameter list
%   <a href="matlab:help smodel/fromDom">smodel/fromDom</a>                  - % Get shape
%   <a href="matlab:help smodel/fromExpression">smodel/fromExpression</a>           - (No help available)
%   <a href="matlab:help smodel/fromStruct">smodel/fromStruct</a>               -  creates from a structure a SMODEL object.
%   <a href="matlab:help smodel/generateConstructorPlist">smodel/generateConstructorPlist</a> -  generates a PLIST from the properties which can rebuild the object.
%   <a href="matlab:help smodel/hessian">smodel/hessian</a>                  -  compute the hessian matrix for a symbolic model.
%   <a href="matlab:help smodel/ifourier">smodel/ifourier</a>                 -  implements continuous f-domain inverse Fourier transform for smodel objects.
%   <a href="matlab:help smodel/ilaplace">smodel/ilaplace</a>                 -  implements continuous s-domain inverse Laplace transform for smodel objects.
%   <a href="matlab:help smodel/inv">smodel/inv</a>                      -  evaluates the inverse of smodel objects.
%   <a href="matlab:help smodel/iztrans">smodel/iztrans</a>                  -  implements continuous z-domain inverse Z-transform for smodel objects.
%   <a href="matlab:help smodel/laplace">smodel/laplace</a>                  -  implements continuous s-domain Laplace transform for smodel objects.
%   <a href="matlab:help smodel/linearize">smodel/linearize</a>                -  output the derivatives of the model relative to the parameters.
%   <a href="matlab:help smodel/loadobj">smodel/loadobj</a>                  -  is called by the load function for user objects.
%   <a href="matlab:help smodel/mergeFields">smodel/mergeFields</a>              -  merges properties (name/values) of smodels
%   <a href="matlab:help smodel/minus">smodel/minus</a>                    -  implements subtraction operator for smodel objects.
%   <a href="matlab:help smodel/mrdivide">smodel/mrdivide</a>                 -  implements mrdivide operator for smodel objects.
%   <a href="matlab:help smodel/mtimes">smodel/mtimes</a>                   -  implements mtimes operator for smodel objects.
%   <a href="matlab:help smodel/op">smodel/op</a>                       -  Add a operation around the model expression
%   <a href="matlab:help smodel/plus">smodel/plus</a>                     -  implements addition operator for smodel objects.
%   <a href="matlab:help smodel/rdivide">smodel/rdivide</a>                  -  implements division operator for smodel objects.
%   <a href="matlab:help smodel/setAliasNames">smodel/setAliasNames</a>            -  Set the property 'aliasNames'
%   <a href="matlab:help smodel/setAliasValues">smodel/setAliasValues</a>           -  Set the property 'aliasValues'
%   <a href="matlab:help smodel/setAliases">smodel/setAliases</a>               -  Set the key-value pairs to the alias-names and alias-values
%   <a href="matlab:help smodel/setExpr">smodel/setExpr</a>                  -  sets the 'expr' property of the smodel object.
%   <a href="matlab:help smodel/setParameters">smodel/setParameters</a>            -  Set some parameters to the symbolic model (smodel) object
%   <a href="matlab:help smodel/setParams">smodel/setParams</a>                -  Set the property 'params' AND 'values'
%   <a href="matlab:help smodel/setTrans">smodel/setTrans</a>                 -  sets the 'trans' property of the smodel object.
%   <a href="matlab:help smodel/setValues">smodel/setValues</a>                -  Set the property 'values'
%   <a href="matlab:help smodel/setXunits">smodel/setXunits</a>                -  sets the 'xunits' property of the smodel object.
%   <a href="matlab:help smodel/setXvals">smodel/setXvals</a>                 -  sets the 'xvals' property of the smodel object.
%   <a href="matlab:help smodel/setXvar">smodel/setXvar</a>                  -  sets the 'xvar' property of the smodel object.
%   <a href="matlab:help smodel/setYunits">smodel/setYunits</a>                -  sets the 'yunits' property of the smodel object.
%   <a href="matlab:help smodel/simplify">smodel/simplify</a>                 -  implements simplify operator for smodel objects.
%   <a href="matlab:help smodel/simplifyUnits">smodel/simplifyUnits</a>            -  simplify the x and/or y units of the model.
%   <a href="matlab:help smodel/smodel">smodel/smodel</a>                   -  constructor for smodel class.
%   <a href="matlab:help smodel/sop">smodel/sop</a>                      -  apply a symbolic operation to the expression.
%   <a href="matlab:help smodel/subs">smodel/subs</a>                     -  substitutes symbolic parameters with the given values.
%   <a href="matlab:help smodel/sum">smodel/sum</a>                      -  adds all the elements of smodel objects arrays.
%   <a href="matlab:help smodel/times">smodel/times</a>                    -  implements multiplication operator for smodel objects.
%   <a href="matlab:help smodel/update_struct">smodel/update_struct</a>            -  update the input structure to the current ltpda version
%   <a href="matlab:help smodel/ztrans">smodel/ztrans</a>                   -  implements continuous z-domain Z-transform for smodel objects.
