%%%%%%%%%%%%%%%%%%%%   class: pest   %%%%%%%%%%%%%%%%%%%%
%
%   <a href="matlab:help pest/attachToDom">pest/attachToDom</a>              - % Create empty pest node with the attribute 'shape'
%   <a href="matlab:help pest/char">pest/char</a>                     -  convert a pest object into a string.
%   <a href="matlab:help pest/combine">pest/combine</a>                  -  combines multiple pest objects.
%   <a href="matlab:help pest/combineExps">pest/combineExps</a>              -  combine the results of different parameter estimation
%   <a href="matlab:help pest/computePdf">pest/computePdf</a>               - computes Probability Density Function from a pest object
%   <a href="matlab:help pest/copy">pest/copy</a>                     -  makes a (deep) copy of the input pest objects.
%   <a href="matlab:help pest/disp">pest/disp</a>                     -  overloads display functionality for pest objects.
%   <a href="matlab:help pest/double">pest/double</a>                   -  overloads double() function for pest objects.
%   <a href="matlab:help pest/eval">pest/eval</a>                     -  evaluate a pest object
%   <a href="matlab:help pest/find">pest/find</a>                     -  Creates analysis objects from the selected parameter(s).
%   <a href="matlab:help pest/fromAOs">pest/fromAOs</a>                  -  construct a pest object from different values.
%   <a href="matlab:help pest/fromDom">pest/fromDom</a>                  - % Get shape
%   <a href="matlab:help pest/fromStruct">pest/fromStruct</a>               -  creates from a structure a PEST object.
%   <a href="matlab:help pest/fromValues">pest/fromValues</a>               -  construct a pest object from different values.
%   <a href="matlab:help pest/generateConstructorPlist">pest/generateConstructorPlist</a> -  generates a PLIST from the properties which can rebuild the object.
%   <a href="matlab:help pest/genericSet">pest/genericSet</a>               -  sets values to a pest property.
%   <a href="matlab:help pest/getY">pest/getY</a>                     -  Get the data property 'y'.
%   <a href="matlab:help pest/jtable">pest/jtable</a>                   -  display the parameters from PEST objects in a java table.
%   <a href="matlab:help pest/loadobj">pest/loadobj</a>                  -  is called by the load function for user objects.
%   <a href="matlab:help pest/mcmcPlot">pest/mcmcPlot</a>                 -  - Tool to visualise results of a MCMC sampling.
%   <a href="matlab:help pest/mve">pest/mve</a>                      - MVE: Minimum Volume Ellipsoid estimator
%   <a href="matlab:help pest/pest">pest/pest</a>                     -  constructor for parameter estimates (pest) class.
%   <a href="matlab:help pest/plot">pest/plot</a>                     -  the pest objects on the given axes.
%   <a href="matlab:help pest/removeParameters">pest/removeParameters</a>         -  removes the named parameters from the pests.
%   <a href="matlab:help pest/setChain">pest/setChain</a>                 - SETCHI2 Set the property 'chain'
%   <a href="matlab:help pest/setChi2">pest/setChi2</a>                  -  Set the property 'chi2'
%   <a href="matlab:help pest/setCorr">pest/setCorr</a>                  -  Set the property 'corr'
%   <a href="matlab:help pest/setCov">pest/setCov</a>                   -  Set the property 'cov'
%   <a href="matlab:help pest/setDof">pest/setDof</a>                   -  Set the property 'dof'
%   <a href="matlab:help pest/setDy">pest/setDy</a>                    -  Set the property 'dy'
%   <a href="matlab:help pest/setDyForParameter">pest/setDyForParameter</a>        -  Sets the according dy-error for the specified parameter.
%   <a href="matlab:help pest/setModels">pest/setModels</a>                -  Set the property 'models'
%   <a href="matlab:help pest/setNames">pest/setNames</a>                 -  Set the property 'names'
%   <a href="matlab:help pest/setPdf">pest/setPdf</a>                   -  Set the property 'pdf'
%   <a href="matlab:help pest/setXvals">pest/setXvals</a>                 -  sets the 'xvals' property of the underlying smodel object.
%   <a href="matlab:help pest/setY">pest/setY</a>                     -  Set the property 'y'
%   <a href="matlab:help pest/setYforParameter">pest/setYforParameter</a>         -  Sets the according y-value for the specified parameter.
%   <a href="matlab:help pest/setYunits">pest/setYunits</a>                -  Set the property 'yunits'
%   <a href="matlab:help pest/setYunitsForParameter">pest/setYunitsForParameter</a>    -  Sets the according y-unit for the specified parameter.
%   <a href="matlab:help pest/simplifyYunits">pest/simplifyYunits</a>           -  simplifies the units of parameters in a pest
%   <a href="matlab:help pest/subset">pest/subset</a>                   -  Extract a subset of parameters from a pest.
%   <a href="matlab:help pest/table">pest/table</a>                    -  display the parameters from PEST objects in a java table.
%   <a href="matlab:help pest/tdChi2">pest/tdChi2</a>                   -  computes the chi-square for a parameter estimate.
%   <a href="matlab:help pest/toLaTeX">pest/toLaTeX</a>                  -  display the parameters from PEST objects in a LaTeX table.
%   <a href="matlab:help pest/update_struct">pest/update_struct</a>            -  update the input structure to the current ltpda version
%   <a href="matlab:help pest/viewResults">pest/viewResults</a>              -  displays the content of the pest object as an html report.
