import logging
from pathlib import Path

from core.config import get_config

logger = logging.getLogger("ltpda")

_PMA_CONFIG_DIR = Path("/app/phpmyadmin-config")
_PMA_CONFIG_FILE = _PMA_CONFIG_DIR / "ltpda.php"


def write_pma_config() -> None:
    """Write a phpMyAdmin PHP config file into the shared volume.

    Sets PmaAbsoluteUri so AJAX calls resolve correctly at /pma/, and disables
    the config storage warning (not needed for this deployment).
    Called on API startup and whenever the public URL is updated via Settings.
    """
    cfg = get_config()
    if not cfg.get("configured") or cfg.get("mysql_mode") != "bundled":
        return
    public_url = (cfg.get("public_url") or "").rstrip("/")
    if not public_url:
        return
    _PMA_CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    _PMA_CONFIG_FILE.write_text(
        "<?php\n"
        "// Generated by LTPDA Repository API — do not edit manually\n"
        f"$cfg['PmaAbsoluteUri'] = '{public_url}/pma/';\n"
        "$cfg['Servers'][1]['pmadb'] = ''; // disable config storage\n"
    )
    logger.info("phpMyAdmin config written: PmaAbsoluteUri = %s/pma/", public_url)
