import logging
from pathlib import Path

from core.config import get_config

logger = logging.getLogger("ltpda")

_PMA_CONFIG_DIR = Path("/app/phpmyadmin-config")
_PMA_CONFIG_FILE = _PMA_CONFIG_DIR / "ltpda.php"


def write_pma_config() -> None:
    """Write a phpMyAdmin PHP config file into the shared volume.

    Always written in bundled mode regardless of whether public_url is set, so
    SSL and config-storage warnings are suppressed from first startup.
    Called on API startup and whenever the public URL is updated via Settings.
    """
    cfg = get_config()
    if not cfg.get("configured") or cfg.get("mysql_mode") != "bundled":
        return
    public_url = (cfg.get("public_url") or "").rstrip("/")
    _PMA_CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    lines = [
        "<?php",
        "// Generated by LTPDA Repository API — do not edit manually",
        "$cfg['PmaNoRelation_DisableWarning'] = true;",
        "$cfg['Servers'][1]['pmadb'] = '';",
    ]
    if public_url:
        lines.append(f"$cfg['PmaAbsoluteUri'] = '{public_url}/pma/';")
    _PMA_CONFIG_FILE.write_text("\n".join(lines) + "\n")
    logger.info(
        "phpMyAdmin config written (public_url=%s)",
        public_url or "not set",
    )
