%%%%%%%%%%%%%%%%%%%%   class: mfh   %%%%%%%%%%%%%%%%%%%%
%
%   <a href="matlab:help mfh/attachToDom">mfh/attachToDom</a>                    - % create empty mfir node with the attribute 'shape'
%   <a href="matlab:help mfh/char">mfh/char</a>                           -  convert a mfh object into a string.
%   <a href="matlab:help mfh/copy">mfh/copy</a>                           -  makes a (deep) copy of the input mfh objects.
%   <a href="matlab:help mfh/declare_objects">mfh/declare_objects</a>                -  declares all constants and sub-functions in the workspace
%   <a href="matlab:help mfh/disp">mfh/disp</a>                           -  overloads display functionality for mfh objects.
%   <a href="matlab:help mfh/elementOp">mfh/elementOp</a>                      -  applies the given operator to the models.
%   <a href="matlab:help mfh/eval">mfh/eval</a>                           - % Check inputs
%   <a href="matlab:help mfh/fisher">mfh/fisher</a>                         -  Calculation of the Fisher Information Matrix/Covariance
%   <a href="matlab:help mfh/flscov">mfh/flscov</a>                         -  - Tool to perform a least square fit in frequency domain.
%   <a href="matlab:help mfh/fminsearch">mfh/fminsearch</a>                     -  uses a simplex search to minimise the given function handle.
%   <a href="matlab:help mfh/fminsearchbnd">mfh/fminsearchbnd</a>                  -  uses a simplex search to minimise the given function handle
%   <a href="matlab:help mfh/fromDom">mfh/fromDom</a>                        - % Get shape
%   <a href="matlab:help mfh/fromStruct">mfh/fromStruct</a>                     -  creates from a structure a COLLECTION object.
%   <a href="matlab:help mfh/function_handle">mfh/function_handle</a>                -  returns a MATLAB function handle version of the function.
%   <a href="matlab:help mfh/generateConstructorPlist">mfh/generateConstructorPlist</a>       -  generates a PLIST from the properties which can rebuild the object.
%   <a href="matlab:help mfh/getFitErrors">mfh/getFitErrors</a>                   -  calculates fisher matrix approximation of fit parameters
%   <a href="matlab:help mfh/getHessian">mfh/getHessian</a>                     -  calculate Hessian matrix for a given function.
%   <a href="matlab:help mfh/getJacobian">mfh/getJacobian</a>                    -  calculate Jacobian matrix for a given function.
%   <a href="matlab:help mfh/lincom">mfh/lincom</a>                         -  make a linear combination of supplied models objects
%   <a href="matlab:help mfh/loadobj">mfh/loadobj</a>                        -  is called by the load function for user objects.
%   <a href="matlab:help mfh/loglikelihood">mfh/loglikelihood</a>                  - LOGLIKELIHOOD: Compute log-likelihood for MFH objects
%   <a href="matlab:help mfh/loglikelihood_ao_td">mfh/loglikelihood_ao_td</a>            - loglikelihood_core_td: Compute log-likelihood for MFH objects
%   <a href="matlab:help mfh/loglikelihood_core">mfh/loglikelihood_core</a>             - loglikelihood_core: Compute log-likelihood for MFH objects
%   <a href="matlab:help mfh/loglikelihood_core_log">mfh/loglikelihood_core_log</a>         - loglikelihood_core_log: Compute log-likelihood for MFH objects
%   <a href="matlab:help mfh/loglikelihood_core_noiseFit_v1">mfh/loglikelihood_core_noiseFit_v1</a> - loglikelihood_core_noiseFit_v1: Compute log-likelihood for MFH objects
%   <a href="matlab:help mfh/loglikelihood_core_student">mfh/loglikelihood_core_student</a>     - loglikelihood_core_student: Compute log-likelihood for MFH objects
%   <a href="matlab:help mfh/loglikelihood_core_td">mfh/loglikelihood_core_td</a>          - loglikelihood_core_td: Compute log-likelihood for MFH objects
%   <a href="matlab:help mfh/loglikelihood_core_whittle">mfh/loglikelihood_core_whittle</a>     - loglikelihood_core_whittle: Compute log-likelihood for MFH objects
%   <a href="matlab:help mfh/loglikelihood_hyper">mfh/loglikelihood_hyper</a>            - loglikelihood_core: Compute log-likelihood for MFH objects
%   <a href="matlab:help mfh/mfh">mfh/mfh</a>                            -  function handle class constructor.
%   <a href="matlab:help mfh/minus">mfh/minus</a>                          -  implements subtraction operator for mfh objects.
%   <a href="matlab:help mfh/multinest">mfh/multinest</a>                      - (No help available)
%   <a href="matlab:help mfh/num2cell">mfh/num2cell</a>                       -  Convert numeric array into cell array.
%   <a href="matlab:help mfh/paramCovMat">mfh/paramCovMat</a>                    -  calculate the covariace matrix for the parameters.
%   <a href="matlab:help mfh/plus">mfh/plus</a>                           -  implements addition operator for mfh objects.
%   <a href="matlab:help mfh/rdivide">mfh/rdivide</a>                        -  implements division operator for mfh objects.
%   <a href="matlab:help mfh/setConstObjects">mfh/setConstObjects</a>                -  sets the 'constObjects' property of a mfh object.
%   <a href="matlab:help mfh/setInputObjects">mfh/setInputObjects</a>                -  sets the 'inputObjects' property of a mfh object.
%   <a href="matlab:help mfh/setNumeric">mfh/setNumeric</a>                     -  sets the 'numeric' property of a mfh object.
%   <a href="matlab:help mfh/setParamsToConst">mfh/setParamsToConst</a>               -  set the given parameters to be constant in the model.
%   <a href="matlab:help mfh/setSubfuncs">mfh/setSubfuncs</a>                    -  sets the 'subfuncs' property of a mfh object.
%   <a href="matlab:help mfh/subsref">mfh/subsref</a>                        - % if we didn't return already, call the built-in MATLAB subsref
%   <a href="matlab:help mfh/testHessianMatrix">mfh/testHessianMatrix</a>              -  Performs a random study of the n-dimensional error ellipsoide for a given confidence level.
%   <a href="matlab:help mfh/times">mfh/times</a>                          -  implements multiplication operator for mfh objects.
%   <a href="matlab:help mfh/update_struct">mfh/update_struct</a>                  -  update the input structure to the current ltpda version
