%
% Tests that simplex algorithm is performing
% in a desirable way.
%
% (Using a simple harmonic oscillator model)
%
function test_MCMC_simplex(~)
  
  result  = true;
  message = 'Pass';
  
  pl = plist(...
    'MHsample',    false,...
    'FitParams',   {'DAMP','K'},...
    'f1',          1e-4,...
    'f2',          0.5,...
    'inNames',     {'COMMAND.force'},...
    'outNames',    {'HARMONIC_OSC_1D.position'},...
    'Navs',        5,...
    'x0',          [0.1 0.1],...
    'simplex',     true,...
    'debug',       false,...
    'jumps',       [2e0 1e1 5e2 1e3],...
    'Display',     'off', ...
    'FunValCheck', 'off', ...
    'MaxIter',     5);
  
  m = MCMC(pl);
  
  % Do a run
  m.setModel(ssm('harmonic_osc.mat'));
  m.setInputs(ao('in.mat'));
  m.setNoise(ao('noise.mat'));
  
  try
    m.process(ao('out.mat'));
  catch err
    result  = false;
    message = sprintf(['Failed to run algorithm.process... ' ...
                       'Error: %s'], err.message);
  end
  
  assert(result, message)

end