%%%%%%%%%%%%%%%%%%%%   class: ssm   %%%%%%%%%%%%%%%%%%%%
%
%   <a href="matlab:help ssm/addParameters">ssm/addParameters</a>                 -  Adds the parameters to the model.
%   <a href="matlab:help ssm/append">ssm/append</a>                        - appends embedded subsytems, with exogenous inputs
%   <a href="matlab:help ssm/assemble">ssm/assemble</a>                      - assembles embedded subsytems, with exogenous inputs
%   <a href="matlab:help ssm/attachToDom">ssm/attachToDom</a>                   - % Create empty ssm node with the attribute 'shape'
%   <a href="matlab:help ssm/blockMatAdd">ssm/blockMatAdd</a>                   - adds corresponding matrices of same sizes or empty inside cell array
%   <a href="matlab:help ssm/blockMatFillDiag">ssm/blockMatFillDiag</a>              - adds corresponding matrices of same sizes or empty inside cell array
%   <a href="matlab:help ssm/blockMatFusion">ssm/blockMatFusion</a>                - fusions a block defined matrix stored inside cell array into one matrix
%   <a href="matlab:help ssm/blockMatIndex">ssm/blockMatIndex</a>                 - adds corresponding matrices of same sizes or empty inside cell array
%   <a href="matlab:help ssm/blockMatMult">ssm/blockMatMult</a>                  - multiplies block defined matrix stored inside cell array
%   <a href="matlab:help ssm/blockMatPrune">ssm/blockMatPrune</a>                 -  selects lines and columns of a block defined matrices stored in a cell array
%   <a href="matlab:help ssm/blockMatRecut">ssm/blockMatRecut</a>                 - cuts a matrix into blocks stored inside cell array
%   <a href="matlab:help ssm/bode">ssm/bode</a>                          -  makes a bode plot from the given inputs to outputs.
%   <a href="matlab:help ssm/bodecst">ssm/bodecst</a>                       -  makes a bodecst plot from the given inputs to outputs.
%   <a href="matlab:help ssm/buildParamPlist">ssm/buildParamPlist</a>               -  builds paramerter plists for the ssm params field.
%   <a href="matlab:help ssm/c2d">ssm/c2d</a>                           -  performs actions on ao objects.
%   <a href="matlab:help ssm/char">ssm/char</a>                          -  convert a ssm object into a string.
%   <a href="matlab:help ssm/copy">ssm/copy</a>                          -  makes a (deep) copy of the input ssm objects.
%   <a href="matlab:help ssm/cpsd">ssm/cpsd</a>                          -  computes the output theoretical CPSD shape with given inputs.
%   <a href="matlab:help ssm/cpsdForCorrelatedInputs">ssm/cpsdForCorrelatedInputs</a>       -  computes the output theoretical CPSD shape with given inputs.
%   <a href="matlab:help ssm/cpsdForIndependentInputs">ssm/cpsdForIndependentInputs</a>      -  computes the output theoretical CPSD shape with given inputs.
%   <a href="matlab:help ssm/d2c">ssm/d2c</a>                           -  performs actions on ao objects.
%   <a href="matlab:help ssm/d2d">ssm/d2d</a>                           -  performs actions on ao objects.
%   <a href="matlab:help ssm/diffStepFish">ssm/diffStepFish</a>                  -  Search for a differantiation step
%   <a href="matlab:help ssm/disp">ssm/disp</a>                          -  display ssm object.
%   <a href="matlab:help ssm/displayProperties">ssm/displayProperties</a>             - DISPAYPROPERTIES displays the ssm model porperties.
%   <a href="matlab:help ssm/doBode">ssm/doBode</a>                        -  makes a bode computation from the given inputs to outputs.
%   <a href="matlab:help ssm/doSetParameters">ssm/doSetParameters</a>               -  Sets the values of the given parameters.
%   <a href="matlab:help ssm/doSimplify">ssm/doSimplify</a>                    -  enables to do model simplification. It is a private function
%   <a href="matlab:help ssm/doSimulate">ssm/doSimulate</a>                    -  simulates a discrete ssm with given inputs
%   <a href="matlab:help ssm/doSubsParameters">ssm/doSubsParameters</a>              -  enables to substitute symbollic patameters
%   <a href="matlab:help ssm/dotview">ssm/dotview</a>                       -   view an ssm object via the DOT interpreter.
%   <a href="matlab:help ssm/double">ssm/double</a>                        - Convert a statespace model object to double arrays for given i/o
%   <a href="matlab:help ssm/duplicateInput">ssm/duplicateInput</a>                -  copies the specified input blocks.
%   <a href="matlab:help ssm/findParameters">ssm/findParameters</a>                -  returns parameter names matching the given pattern.
%   <a href="matlab:help ssm/fisher">ssm/fisher</a>                        -  Fisher matrix calculation for SSMs.
%   <a href="matlab:help ssm/fromDom">ssm/fromDom</a>                       - % Get shape
%   <a href="matlab:help ssm/fromStruct">ssm/fromStruct</a>                    -  creates from a structure an SSM object.
%   <a href="matlab:help ssm/generateConstructorPlist">ssm/generateConstructorPlist</a>      -  generates a PLIST from the properties which can rebuild the object.
%   <a href="matlab:help ssm/getParameters">ssm/getParameters</a>                 -  returns parameter values for the given names.
%   <a href="matlab:help ssm/getParams">ssm/getParams</a>                     -  returns the parameter list for this SSM model.
%   <a href="matlab:help ssm/getPortNamesForBlocks">ssm/getPortNamesForBlocks</a>         -  returns a list of port names for the given block.
%   <a href="matlab:help ssm/isStable">ssm/isStable</a>                      -  tells if ssm is numerically stable
%   <a href="matlab:help ssm/kalman">ssm/kalman</a>                        -  applies Kalman filtering to a discrete ssm with given i/o
%   <a href="matlab:help ssm/loadobj">ssm/loadobj</a>                       -  is called by the load function for user objects.
%   <a href="matlab:help ssm/loglikelihood">ssm/loglikelihood</a>                 - LOGLIKELIHOOD: Compute log-likelihood for SSM objects
%   <a href="matlab:help ssm/loglikelihood_core">ssm/loglikelihood_core</a>            - LOGLIKELIHOOD: Compute log-likelihood for SSM objects
%   <a href="matlab:help ssm/modelHelper_checkParameters">ssm/modelHelper_checkParameters</a>   -  compare the user requested parameter names to
%   <a href="matlab:help ssm/modelHelper_declareParameters">ssm/modelHelper_declareParameters</a> -  builds parameters plists for the ssm params field.
%   <a href="matlab:help ssm/modelHelper_processInputPlist">ssm/modelHelper_processInputPlist</a> -  processes the input parameters plists for
%   <a href="matlab:help ssm/modifyTimeStep">ssm/modifyTimeStep</a>                -  modifies the timestep of a ssm object
%   <a href="matlab:help ssm/optimiseForFitting">ssm/optimiseForFitting</a>            -  reduces the system matrices to doubles and strings.
%   <a href="matlab:help ssm/parameterDiff">ssm/parameterDiff</a>                 -  Makes a ssm that produces the output and state derivatives.
%   <a href="matlab:help ssm/projectNoise">ssm/projectNoise</a>                  -  performs actions on ao objects.
%   <a href="matlab:help ssm/psd">ssm/psd</a>                           -  computes the output theoretical PSD shape with given inputs.
%   <a href="matlab:help ssm/removeEmptyBlocks">ssm/removeEmptyBlocks</a>             -  enables to do model simplification
%   <a href="matlab:help ssm/reorganize">ssm/reorganize</a>                    - REOGANIZE rearranges a ssm object for fast input to BODE, SIMULATE, PSD.
%   <a href="matlab:help ssm/reshuffle">ssm/reshuffle</a>                     -  rearragnes a ssm object using the given inputs and outputs.
%   <a href="matlab:help ssm/reshuffleSym">ssm/reshuffleSym</a>                  -  rearragnes a ssm object using the given inputs and outputs.
%   <a href="matlab:help ssm/resp">ssm/resp</a>                          -  gives the timewise impulse response of a statespace model.
%   <a href="matlab:help ssm/respcst">ssm/respcst</a>                       -  gives the timewise impulse response of a statespace model.
%   <a href="matlab:help ssm/sMinReal">ssm/sMinReal</a>                      -  gives a minimal realization of a ssm object by deleting unreached states
%   <a href="matlab:help ssm/setA">ssm/setA</a>                          -  sets the A matrices to be the given cell array.
%   <a href="matlab:help ssm/setB">ssm/setB</a>                          -  sets the B matrices to be the given cell array.
%   <a href="matlab:help ssm/setBlockProperties">ssm/setBlockProperties</a>            -  Sets the specified properties of the specified SSM blocks.
%   <a href="matlab:help ssm/setC">ssm/setC</a>                          -  sets the C matrices to be the given cell array.
%   <a href="matlab:help ssm/setD">ssm/setD</a>                          -  sets the D matrices to be the given cell array.
%   <a href="matlab:help ssm/setParameters">ssm/setParameters</a>                 -  Sets the values of the given parameters.
%   <a href="matlab:help ssm/setParams">ssm/setParams</a>                     -  Sets the parameters of the model to the given plist.
%   <a href="matlab:help ssm/setPortProperties">ssm/setPortProperties</a>             -  Sets names of the specified SSM ports.
%   <a href="matlab:help ssm/settlingTime">ssm/settlingTime</a>                  -  retunrns 1% the settling time of the system.
%   <a href="matlab:help ssm/simplify">ssm/simplify</a>                      -  enables to do model simplification
%   <a href="matlab:help ssm/simulate">ssm/simulate</a>                      -  simulates a discrete ssm with given inputs
%   <a href="matlab:help ssm/ssm">ssm/ssm</a>                           -  statespace model class constructor.
%   <a href="matlab:help ssm/ssm2dot">ssm/ssm2dot</a>                       -  converts a statespace model object a DOT file.
%   <a href="matlab:help ssm/ssm2miir">ssm/ssm2miir</a>                      -  converts a statespace model object to a miir object
%   <a href="matlab:help ssm/ssm2pzmodel">ssm/ssm2pzmodel</a>                   -  converts a time-continuous statespace model object to a pzmodel
%   <a href="matlab:help ssm/ssm2rational">ssm/ssm2rational</a>                  -  converts a statespace model object to a rational frac. object
%   <a href="matlab:help ssm/ssm2ss">ssm/ssm2ss</a>                        -  converts a statespace model object to a MATLAB statespace object.
%   <a href="matlab:help ssm/ssmFromDescription">ssm/ssmFromDescription</a>            - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help ssm/ssmFromMiir">ssm/ssmFromMiir</a>                   - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help ssm/ssmFromParfrac">ssm/ssmFromParfrac</a>                - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help ssm/ssmFromPzmodel">ssm/ssmFromPzmodel</a>                - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help ssm/ssmFromRational">ssm/ssmFromRational</a>               - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help ssm/ssmFromss">ssm/ssmFromss</a>                     - %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%   <a href="matlab:help ssm/steadyState">ssm/steadyState</a>                   -  returns a possible value for the steady state of an ssm.
%   <a href="matlab:help ssm/subsParameters">ssm/subsParameters</a>                -  enables to substitute symbolic patameters
%   <a href="matlab:help ssm/update_struct">ssm/update_struct</a>                 -  update the input structure to the current ltpda version
%   <a href="matlab:help ssm/validate">ssm/validate</a>                      -  Completes and checks the content a ssm object
%   <a href="matlab:help ssm/viewDetails">ssm/viewDetails</a>                   -  performs actions on ssm objects.
