%%%%%%%%%%%%%%%%%%%%   class: matrix   %%%%%%%%%%%%%%%%%%%%
%
%   <a href="matlab:help matrix/attachToDom">matrix/attachToDom</a>              - % Create empty matrix node with the attribute 'shape'
%   <a href="matlab:help matrix/char">matrix/char</a>                     -  convert a matrix object into a string.
%   <a href="matlab:help matrix/clearObjHistories">matrix/clearObjHistories</a>        -  Clear the history of the inside objects.
%   <a href="matlab:help matrix/cohere">matrix/cohere</a>                   -  estimates the coherence between elements of the vector.
%   <a href="matlab:help matrix/copy">matrix/copy</a>                     -  makes a (deep) copy of the input matrix objects.
%   <a href="matlab:help matrix/cpsd">matrix/cpsd</a>                     -  estimates the cross-spectral density between elements of the vector.
%   <a href="matlab:help matrix/crb">matrix/crb</a>                      -  computes the inverse of the Fisher Matrix
%   <a href="matlab:help matrix/cross">matrix/cross</a>                    -  implements cross operator for matrix objects.
%   <a href="matlab:help matrix/ctranspose">matrix/ctranspose</a>               -  implements conjugate transpose operator for matrix objects.
%   <a href="matlab:help matrix/delay">matrix/delay</a>                    -  overloads ao/delay for matrix objects.
%   <a href="matlab:help matrix/det">matrix/det</a>                      -  evaluates the determinant for matrix object.
%   <a href="matlab:help matrix/disp">matrix/disp</a>                     -  overloads display functionality for matrix objects.
%   <a href="matlab:help matrix/dispersion">matrix/dispersion</a>               -  computes the dispersion function
%   <a href="matlab:help matrix/dispersionLoop">matrix/dispersionLoop</a>           -  computes the dispersion function
%   <a href="matlab:help matrix/double">matrix/double</a>                   -  - converts a matrix of objects into matrix of numbers
%   <a href="matlab:help matrix/elementOp">matrix/elementOp</a>                -  applies the given operator to the input matrices.
%   <a href="matlab:help matrix/fftfilt">matrix/fftfilt</a>                  -  fft filter for matrix objects
%   <a href="matlab:help matrix/filter">matrix/filter</a>                   -  implements N-dim filter operator for matrix objects.
%   <a href="matlab:help matrix/filtfilt">matrix/filtfilt</a>                 -  overrides the filtfilt function for matrices of analysis objects.
%   <a href="matlab:help matrix/fisher">matrix/fisher</a>                   -  Fisher matrix calculation for MATRIX models.
%   <a href="matlab:help matrix/flscovSegments">matrix/flscovSegments</a>           -  - Tool to perform a least square fit in frequency domain
%   <a href="matlab:help matrix/fromDom">matrix/fromDom</a>                  - % Get shape
%   <a href="matlab:help matrix/fromInput">matrix/fromInput</a>                - Construct a matrix object from ltpda_uoh objects.
%   <a href="matlab:help matrix/fromStruct">matrix/fromStruct</a>               -  creates from a structure a MATRIX object.
%   <a href="matlab:help matrix/fromValues">matrix/fromValues</a>               - Construct a matrix object with multiple AOs built from input values.
%   <a href="matlab:help matrix/generateConstructorPlist">matrix/generateConstructorPlist</a> -  generates a PLIST from the properties which can rebuild the object.
%   <a href="matlab:help matrix/getObjectAtIndex">matrix/getObjectAtIndex</a>         -  index into the inner objects of one matrix object.
%   <a href="matlab:help matrix/inv">matrix/inv</a>                      -  evaluates the inverse for matrix object.
%   <a href="matlab:help matrix/iplot">matrix/iplot</a>                    -  calls ao/iplot on all inner ao objects.
%   <a href="matlab:help matrix/lcohere">matrix/lcohere</a>                  -  estimates the coherence between elements of the vector using
%   <a href="matlab:help matrix/lcpsd">matrix/lcpsd</a>                    -  estimates the coherence between elements of the vector using a
%   <a href="matlab:help matrix/lincom">matrix/lincom</a>                   -  make a linear combination of analysis objects
%   <a href="matlab:help matrix/linearize">matrix/linearize</a>                -  output the derivatives of the model relative to the parameters.
%   <a href="matlab:help matrix/linfitsvd">matrix/linfitsvd</a>                -  Linear fit with singular value decomposition
%   <a href="matlab:help matrix/linlsqsvd">matrix/linlsqsvd</a>                -  Linear least squares with singular value decomposition
%   <a href="matlab:help matrix/loadobj">matrix/loadobj</a>                  -  is called by the load function for user objects.
%   <a href="matlab:help matrix/loglikelihood">matrix/loglikelihood</a>            - LOGLIKELIHOOD: Compute log-likelihood for MATRIX objects
%   <a href="matlab:help matrix/loglikelihood_core">matrix/loglikelihood_core</a>       - loglikelihood: Compute log-likelihood for MATRIX objects
%   <a href="matlab:help matrix/lscov">matrix/lscov</a>                    -  is a wrapper for MATLAB's lscov function.
%   <a href="matlab:help matrix/ltfe">matrix/ltfe</a>                     -  estimates the transfer function between elements of the vector using
%   <a href="matlab:help matrix/matrix">matrix/matrix</a>                   -  constructor for matrix class.
%   <a href="matlab:help matrix/mchNoisegen">matrix/mchNoisegen</a>              -  Generates multichannel noise data series given a model
%   <a href="matlab:help matrix/mchNoisegenFilter">matrix/mchNoisegenFilter</a>        -  Construct a matrix filter from cross-spectral density matrix
%   <a href="matlab:help matrix/mcmc">matrix/mcmc</a>                     -  estimates paramters using a Monte Carlo Markov Chain.
%   <a href="matlab:help matrix/mean">matrix/mean</a>                     -  evaluates the meanerse for matrix object.
%   <a href="matlab:help matrix/minus">matrix/minus</a>                    -  implements subtraction operator for ltpda model objects.
%   <a href="matlab:help matrix/modelSelect">matrix/modelSelect</a>              -  - method to compute the Bayes Factor using RJMCMC, LF, LM, SBIC methods
%   <a href="matlab:help matrix/mtimes">matrix/mtimes</a>                   -  implements mtimes operator for matrix objects.
%   <a href="matlab:help matrix/osize">matrix/osize</a>                    -  Returns the size of the inner object array.
%   <a href="matlab:help matrix/plot">matrix/plot</a>                     -  the matrix objects on the given axes.
%   <a href="matlab:help matrix/plus">matrix/plus</a>                     -  implements addition operator for matrix objects.
%   <a href="matlab:help matrix/power">matrix/power</a>                    - TIMES implements multiplication operator for matrix objects.
%   <a href="matlab:help matrix/rdivide">matrix/rdivide</a>                  -  implements division operator for matrix objects.
%   <a href="matlab:help matrix/rotate">matrix/rotate</a>                   -  applies rotation factor to matrix objects
%   <a href="matlab:help matrix/setObjs">matrix/setObjs</a>                  -  sets the 'objs' property of a matrix object.
%   <a href="matlab:help matrix/simplify">matrix/simplify</a>                 -  each model in the matrix.
%   <a href="matlab:help matrix/spsdSubtraction">matrix/spsdSubtraction</a>          -  makes a sPSD-weighted least-square iterative fit
%   <a href="matlab:help matrix/tdfit">matrix/tdfit</a>                    -  fit a MATRIX of transfer function SMODELs to a matrix of input and output signals.
%   <a href="matlab:help matrix/tfe">matrix/tfe</a>                      -  estimates the transfer functions between elements of the vector.
%   <a href="matlab:help matrix/times">matrix/times</a>                    -  implements multiplication operator for matrix objects.
%   <a href="matlab:help matrix/toArray">matrix/toArray</a>                  -  unpacks the objects in a matrix and places them into a MATLAB
%   <a href="matlab:help matrix/transpose">matrix/transpose</a>                -  implements transpose operator for matrix objects.
%   <a href="matlab:help matrix/unpack">matrix/unpack</a>                   -  unpacks the objects in a matrix and sets them to the given output
%   <a href="matlab:help matrix/update_struct">matrix/update_struct</a>            -  update the input structure to the current ltpda version
%   <a href="matlab:help matrix/wrapperEval">matrix/wrapperEval</a>              - % loop over inner objects
%   <a href="matlab:help matrix/xspec">matrix/xspec</a>                    - MATRIX/XSPEC applies the given cross-spectral density method to the vecor
